### ISSUE TITLE
External DAC incompatibility

### ISSUE THREAD

**Issue by hugodcpires** [Pittvandewitt/Wavelet#10]
Using a USB DAC (in my case, Topping NX4) the audio output is noisy. Without the DAC audio output is fine. The DAC also sounds fine if Wavelet is not used (including with Viper4android). Maybe the sample bit depth used by Wavelet doesn't match the bit depth Android is driving the DAC with?

**Comment by Pittvandewitt** [comment]
If this is the case, it would be a limitation in the libraries used or the audio framework. It may even be system dependent.
I used Wavelet with my Dragonfly Red without issues. 
I understand that this information won't fix the issue, but there is nothing I can fix either, hence I'll close it.

**Comment by hugodcpires** [comment]
No problem, I'll just continue using Viper4android. It would be nice to have the same functionality for non-root users though.Cheers, Hugo On 20 May 2020 10:41, "Thomas W." <notifications@github.com> wrote:
If this is the case, it would be a limitation in the libraries used or the audio framework. It may even be system dependent.
I used Wavelet with my Dragonfly Red without issues.
I understand that this information won't fix the issue, but there is nothing I can fix either, hence I'll close it.
