### ISSUE TITLE
Android 11 - auto start

### ISSUE THREAD

**Issue by davebanthorpe** [Pittvandewitt/Wavelet#102]
Hi. On Android 10, this app would auto start if it detected music e.g from Spotify. Upgraded to 11 and I have to manually turn it on before it works. I have enabled both notification access and dump access.

Am I expecting it to do something it should not?

I.e. should I always have to open wavelet and press the power button in the app (goes from red to green)?

**Comment by Pittvandewitt** [comment]
Short answer is yes. You now have to manually enable Wavelet if you want to apply audio effects to your music. You can also disable it and renable it whenever desired. This was not possible in previous versions.

You can head over to this issue for more context #91
