### ISSUE TITLE
Support for Plexamp & Plex

### ISSUE THREAD

**Issue by kmscode** [Pittvandewitt/Wavelet#11]
[Plexamp](https://plexamp.com/) is my preferred Music Player and it is of course closely associated with the full [Plex Media App](https://www.plex.tv/media-server-downloads/#plex-app).

I would love for these apps to be supported without Legacy mode if possible.

I did see a comment from you in the XDA forum regarding app support - that the media app needs to add session broadcasting to their apps. If there is nothing for you to do to get these apps to work, could you reply here with a bit more info about session broadcasting that I can pass on to the Plex team? Thanks in advance!

PS - Tested with Spotify on my Bose Soundsport Wireless -- this is a fantastic app! THANKS!

**Comment by Pittvandewitt** [comment]
Glad to hear you're enjoying the app!
You're right on the session broadcasting. I posted a bug report in the Spotify forums some time ago on this same topic, I highly recommend you check it out: https://community.spotify.com/t5/Ongoing-Issues/Android-Audio-sessions-are-not-opened-and-closed-properly/idi-p/4861998
If you need some more guidance, let me know.

**Comment by kmscode** [comment]
Thanks for the quick response! This is exactly the info that I was looking for.

As there is nothing for you to do within the app, I'll close issue out.
