### ISSUE TITLE
Graphic EQ Constant Q Value

### ISSUE THREAD

**Issue by chrsmlls333** [Pittvandewitt/Wavelet#113]
I'm generating a preset with AutoEQ and while I can target all the bands in the Graphic Equalizer, I just wanted to confirm what constant Q is used on the backend? I'm a noob at all this, so is it simply 1 when it comes to fixed-band eqs?

Thanks for any help!

**Comment by chrsmlls333** [comment]
I had not seen the guide, oops.

**Comment by shellusc** [comment]
I hate to ask, but what is the Q for the graphicEQ?
I really cant find any information about it...
