### ISSUE TITLE
Bass booster and reverberation not present

### ISSUE THREAD

**Issue by iam1004yang** [Pittvandewitt/Wavelet#114]
Phone: LG Q92
Headphones: Sony MDR-1a

![Screenshot_20211008-200920~2.png](https://user-images.githubusercontent.com/46566770/136645169-60d5daba-729a-4f89-9f1e-17c4d7213498.png)
(Well, I am using Korean version app)

I have been using the app with premium features for about a month, but I recently found out that bass booster and reverberation features were not present from the begining.

Is there a way to solve this problem?

Thanks.

**Comment by Pittvandewitt** [comment]
Reverberation is available only if legacy mode is disabled.
The bass booster is available for Android 9 only. The library used for this effect was changed with the Android 10 update and does no longer meet the standards I wish to provide in Wavelet.
