### ISSUE TITLE
Request: Provide option to disable toasts

### ISSUE THREAD

**Issue by yoinx** [Pittvandewitt/Wavelet#115]
Please provide an option to allow users to disable the toast messages. 

While I enjoy wavelet I don't need it to tell me when it can't provide me with effects processing everytime that I open an app that it doesn't like. It happens quite a bit now that I've installed Microsoft Teams, literally everything I go into a text chat (with no audio) wavelet is courteous enough to let me know that it can't process the non-existent audio.

This also happens frequently in my dialer and a few other apps that I can't think of. 

Yes, all permissions (dump, notification) have been granted and the app works great with Spotify like I want.

**Comment by Pittvandewitt** [comment]
The behaviour in the next version will be changed. Only if one or more audio effects could not be instantiated but at least one could, a toast message will be displayed. All failed effects will be bundled into a single message too, greatly reducing the amount of toast messages.
