### ISSUE TITLE
What is the behavior of Wavelet when dealing with extremely high positive gain?

### ISSUE THREAD

**Issue by ehfd** [Pittvandewitt/Wavelet#118]
AutoEq normally restricts maximum positive gain with the `--max_gain` parameter set as +6 dB. However, there are frequently situations where maximum positive gain could go higher, when the sensitivity of the headphone is high enough for the output volume to go as loud as most people prefer without going to maximum digital volume even with the huge negative digital preamp.

What is intended to be done: https://www.reddit.com/r/headphones/comments/hyyu34/i_did_not_know_my_koss_ksc_75_could_take_a_bass/

This specific headphone model, for instance, responds well to EQ for boosting its sub-bass frequencies. Thus a high maximum positive gain can be very useful. The below is when the `--max_gain` parameter is set as +10 dB. It can be seen that in order for all of the curve to be compensated to the Harman curve, the `--max_gain` parameter should be at least +15 dB.

![image](https://user-images.githubusercontent.com/8457324/139435466-a23b4127-e71d-472b-8f01-231aa0d43126.png)

```GraphicEQ: 20 -0.2; 21 -0.2; 22 -0.2; 23 -0.2; 24 -0.2; 26 -0.2; 27 -0.2; 29 -0.2; 30 -0.2; 32 -0.2; 34 -0.2; 36 -0.2; 38 -0.2; 40 -0.2; 43 -0.2; 45 -0.2; 48 -0.7; 50 -1.3; 53 -2.2; 56 -3.0; 59 -3.7; 63 -4.6; 66 -5.1; 70 -5.7; 74 -6.1; 78 -6.6; 83 -7.2; 87 -7.8; 92 -8.4; 97 -9.0; 103 -9.6; 109 -10.1; 115 -10.5; 121 -10.9; 128 -11.3; 136 -11.6; 143 -11.8; 151 -12.0; 160 -12.2; 169 -12.3; 178 -12.4; 188 -12.4; 199 -12.5; 210 -12.5; 222 -12.4; 235 -12.3; 248 -12.2; 262 -12.0; 277 -11.7; 292 -11.5; 309 -11.2; 326 -11.0; 345 -10.7; 364 -10.5; 385 -10.3; 406 -10.1; 429 -9.9; 453 -9.7; 479 -9.6; 506 -9.4; 534 -9.2; 565 -9.0; 596 -8.9; 630 -8.7; 665 -8.6; 703 -8.6; 743 -8.5; 784 -8.5; 829 -8.5; 875 -8.5; 924 -8.5; 977 -8.6; 1032 -8.6; 1090 -8.6; 1151 -8.7; 1216 -8.7; 1284 -8.7; 1357 -8.7; 1433 -8.9; 1514 -9.1; 1599 -9.2; 1689 -9.4; 1784 -9.6; 1885 -9.9; 1991 -10.1; 2103 -10.4; 2221 -10.6; 2347 -10.8; 2479 -10.8; 2618 -10.7; 2766 -10.6; 2921 -10.5; 3086 -10.6; 3260 -11.0; 3443 -10.7; 3637 -9.4; 3842 -8.2; 4058 -8.9; 4287 -10.4; 4528 -12.3; 4783 -13.3; 5052 -12.3; 5337 -11.7; 5637 -11.4; 5955 -11.0; 6290 -10.7; 6644 -10.2; 7018 -10.0; 7414 -10.4; 7831 -10.4; 8272 -10.1; 8738 -10.1; 9230 -10.4; 9749 -10.9; 10298 -11.4; 10878 -11.8; 11490 -12.3; 12137 -12.9; 12821 -13.6; 13543 -14.3; 14305 -15.1; 15110 -16.0; 15961 -17.0; 16860 -18.0; 17809 -19.1; 18812 -20.3; 19871 -21.5```

The convolutional EQ (EqualizerAPO GraphicEQ) configuration seems to have taken the preamp into account, since there is no parameter that goes above 0 dB. However, when the same file is loaded on Wavelet, the graph seems to get reverted to what the graph generated in AutoEq shows.
When a new EQ configuration is generated by AutoEq after the maximum positive gain is set to +12 dB or +15 dB, the graph goes outside the Wavelet application interface.

Now, the question is, can Wavelet accommodate high maximum gain like over +20 dB or so? Can it clip when this happens? Does Wavelet take the the preamp into account, preventing it from strange effects, or does it not?
The concerning question for Wavelet: https://www.reddit.com/r/oratory1990/comments/mf1qkt/comment/gxqygl8/
This post seems to claim that Wavelet's preamp configuration is indeed ambiguous and that the "Channel Balance" option should instead be used. This might mean anything from clipping actually happening to the volume becoming so loud that potentially hearing loss can happen.

It would be great if whether this potential issue exists can be clarified. Thank you very much in advance.

**Comment by Pittvandewitt** [comment]
All values between 100 and 10000Hz are taken into account when importing a file in Wavelet and are normalized at 0dB, just like the results that can be found in the hesuvi.zip file from the AutoEq repository.
If you are worried about clipping/volume issues, you should enable the limiter to prevent this from happening. The post-gain option can then be set to reduce the output volume and change when the limiter would kick in.
The channel balance option can also be used to further reduce the volume if desired.

**Comment by ehfd** [comment]
> All values between 100 and 10000Hz are taken into account when importing a file in Wavelet and are normalized at 0dB, just like the results that can be found in the hesuvi.zip file from the AutoEq repository.
1. Does it mean the values <100 Hz and >10 kHz are excluded from equalization? Or do they still get equalized?

> If you are worried about clipping/volume issues, you should enable the limiter to prevent this from happening. The post-gain option can then be set to reduce the output volume and change when the limiter would kick in. The channel balance option can also be used to further reduce the volume if desired.

> https://sourceforge.net/p/equalizerapo/discussion/general/thread/ecb6996a/#e08a In theory, the audio output by an application can reach a maximum of 0 dB (1.0), so increasing this value further using E-APO would introduce clipping. You could try this out using Audacity by generating a sound file with amplitude 0dB (using the signal generator). Increasing the preamp while playing this file should not increase the heard volume as Windows' integrated limiter should be in action then. If the volume you hear still increases then there must be something in the audio driver or its own APOs that reduces the volume and you can use E-APO to workaround that by seeing how much you can increase the preamp while hearing a volume increase.

2. Is it safe to assume that that the audio output does not go past 0 dB after your normalization of GraphicEQ parameters then?

**Comment by ehfd** [comment]
I tried this myself and seems to have not much issues with this. Thanks a lot for the answer.
