### ISSUE TITLE
Missing model in Wavelet, present in AutoEQ repo

### ISSUE THREAD

**Issue by Silver-Fullbuster** [Pittvandewitt/Wavelet#12]
The model `Sennheiser CX 180 Street II` is present in the AutoEQ repo, but isn't present in the Wavelet app to equalize for. Is it pending addition or was it accidentally missed?

**Comment by Pittvandewitt** [comment]
[This commit](https://github.com/jaakkopasanen/AutoEq/commit/777b287764198427420c70509eab856da7d781c1) opens the pave for adding data from reference audio analyzer. It will be added in a next update.
