### ISSUE TITLE
Does not work on DX300

### ISSUE THREAD

**Issue by JoonSumisu** [Pittvandewitt/Wavelet#122]
Hi Pittvandewitt, thank for your great work, it works fantastic on my phone

but wavelet does not function on ibasso dx300, though it is likely the problem of this music player, wavelet fails to instantiate the dynamicsprocessing and fails to visit the severs(error -1), it that anything I can do for making wavelet work on this music player?

**Comment by Pittvandewitt** [comment]
That is a real shame that it does not work as expected on the DX300. I assume it would have been a killer package.
If the DynamicsProcessing instantation fails, it probably means that this effect is removed from the ROM system. I will not be able to change this. The error -1 occurs if there is an error connecting to the Google Play billing servers.
