### ISSUE TITLE
Issue with the limiter

### ISSUE THREAD

**Issue by RightL** [Pittvandewitt/Wavelet#123]
The effect of the limiter seems to depend on system volume. When the volume is low, there is hardly any effect even with threshold set to -30 db.
But the limiter seems to work well when using a bluetooth headphone with 'sync volume with phone' enabled. The threshold volume is determined by the playing content, not system volume.
So I wonder if it's possible to set threshold lower than -30db or make it works like bluetooth ?
Thanks

**Comment by Pittvandewitt** [comment]
Wavelet uses a system implementation and there is no option to change the behavior you're specifying.
Perhaps you can take a look at the 'disable absolute volume' option in your device developer settings.
