### ISSUE TITLE
[Feature request] - Equal loudness compensation plugin

### ISSUE THREAD

**Issue by aqxa1** [Pittvandewitt/Wavelet#127]
Hi,
A plugin that compensations for changing loudness perception at different volume levels would be nice. Along the lines of this [loud-comp-stereo lsp-plugin](https://lsp-plug.in/?page=manuals&section=loud_comp_stereo) and the corresponding [discussion](https://github.com/sadko4u/lsp-plugins/issues/81). In essence, by changing the volume level, the frequency response would be adjusted based on equal oudness curves: ![equal loudness curves](https://user-images.githubusercontent.com/12834464/77921242-2f307b00-72a8-11ea-886e-d60c2611e593.png) with mids essentially being lowered relative to bass (and treble to a lesser extent) as volume is lowered, in line with hearing being less sensitive to those frequencies at lower volume levels.

**Comment by Pittvandewitt** [comment]
Version 23.11 introduces the equal loudness feature. It is available in the beta test.
