### ISSUE TITLE
Cambridge Audio "Melomania 1" crashes Wavelet App

### ISSUE THREAD

**Issue by boro2000** [Pittvandewitt/Wavelet#13]
As soon I am connecting my "Melomania 1" headphones via bluetooth, the Wavelet-App crashes.
The problem seems to be the two `/` characters in the device name `Melomania L // Cambridge`. 
These cause failure in function `makeFilename` when creating the xml profile file.

Hope that helps to get rid of this bug :)

See the following screen shots:
![Screenshot_20200521-162316_Market Feedback Agent](https://user-images.githubusercontent.com/28839768/82570150-8274ca80-9b81-11ea-8b9c-5b3785423794.jpg)

![Screenshot_20200521-162247_Market Feedback Agent](https://user-images.githubusercontent.com/28839768/82569837-0ed2bd80-9b81-11ea-8d1c-0f0f1c8144a3.jpg)

**Comment by Pittvandewitt** [comment]
That's a very interesting edge case indeed. Thank you very much for reporting the issue and providing the screenshot. The Play Console doesn't provide enough information to solve it, but this does.
I will make sure to fix this first.

**Comment by Pittvandewitt** [comment]
I pushed a new build with the fix included. It should be available in a few hours.

**Comment by boro2000** [comment]
I can confirm this now works perfectly :) Also, many thanks for the Melomania 1 audio profile.

**Comment by Pittvandewitt** [comment]
In the screenshot you provide, it shows the device name as Melomania L // Cambridge.
Is the L the left earphone paired? If yes, does it say 'Melomania R // Cambridge' when the right earphone is paired?

**Comment by RainbowMiner** [comment]
It shows the device name of the earphone, which connects first. So both device names are valid.

**Comment by Pittvandewitt** [comment]
Thank you for your input. I will remove the L and R from the file name in which the settings are saved. This way you don't have to synchronize the settings manually anymore.
