### ISSUE TITLE
Wrong headphone model is displayed

### ISSUE THREAD

**Issue by Noexpert** [Pittvandewitt/Wavelet#135]
When I select "Etymotic ER2S**E**", "Etymotic ER2S**R**" is displayed instead.

**Comment by Pittvandewitt** [comment]
The er2sr is a duplicate of the er2se data, which means you can choose either one. It seems that the er2sr does not even exist. The data will be removed in a future update.

**Comment by Pittvandewitt** [comment]
Fixed in the latest update which will be available in the coming days.
