### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by harvasyuk** [Pittvandewitt/Wavelet#138]
Is it possible to decrease memory usage?

This is ram usage when Wavelet isn't active (no music playing and headphones not connected)
![Screenshot_20220119-123256](https://user-images.githubusercontent.com/17803706/150114706-7f265dbc-6aa2-42b8-b922-175fa466957d.png)

**Comment by harvasyuk** [comment]
Most time it shows around 200-300mb. But sometimes it's like on the screenshot

**Comment by ThatBum** [comment]
Mine has gone over 1GB
![Screenshot_20220225-053910](https://user-images.githubusercontent.com/4646042/155725174-178bcce8-81a8-4546-aa95-acc225162013.png)

**Comment by Pittvandewitt** [comment]
An issue with these symptoms has been resolved in the april update (22.04). If you still encounter these symptoms, please let me know. Don't forget to mention which session detection mode you use (enhanced, legacy or default).

**Comment by mirh** [comment]
Could still be better. 
Play Store's InAppBillingService usually takes 100-200MB alone. 

I also found that you can trigger a sizeable usage increase when you switch the system language.

**Comment by mirh** [comment]
It's even worse than I was expecting. 
![Screenshot_20220602-034827](https://user-images.githubusercontent.com/9366725/171625938-d23b5c8f-52ed-446f-b5a7-bb23d294c1c2.png)
