### ISSUE TITLE
[Feature Request]: Parametric EQ for AutoEQ and as standalone option

### ISSUE THREAD

**Issue by christianmende** [Pittvandewitt/Wavelet#139]
Would be nice to see a parametric eq option for AutoEQ since all the measurements are build for parametric eq, as well. Would be way more accurate.  And like the "Graphical EQ" module, it would be nice if there would be the option for a seperate standalone parametric eq module (maybe would be better if you just can switch between Graphical and Parametric EQ).

Regards

**Comment by 1sad** [comment]
would be very nice
reading through issues it appears it might not be possible though, cause android apparently has no support for PEQ and is just emulating it with many bands?
would be nice to interact with it natively though. right now i think you have to make faux PEQ presets on pc and convert them into wavelet format using another program [https://github.com/zettonaender/eqapotographiceq-gui](url)
maybe some way to integrate this into wavelet?

**Comment by Pittvandewitt** [comment]
@1sad your assumption is correct.
If you wish to convert your preset in a format you can import in Wavelet, I recommend checking out the AutoEq tool here: https://github.com/jaakkopasanen/AutoEq/blob/master/README.md
