### ISSUE TITLE
Issue: Wavelet was unable to instantiate PresetReverb Effects error on each load

### ISSUE THREAD

**Issue by Akshaychdev** [Pittvandewitt/Wavelet#143]
* Pro version
* Android 11 - MIUI 12.5
* With poweramp and other players, (musicfx on, DVC off poweramp)

![Screenshot_2022-01-24-18-36-13-986_com pittvandewitt wavelet-01](https://user-images.githubusercontent.com/63786863/150788467-49869949-46a3-4b8a-bd87-de169f6958bf.jpeg)

**Comment by hmnd** [comment]
Experiencing this as well on a Pixel 5 running Android 12.1.

**Comment by ThatBum** [comment]
Am also having this issue, but with Virtualizer unable to instantize in addition to PresetReverb.
![Bug report](https://i.imgur.com/1Ji0oHb.png)
Device is a Pixel 6 Pro, audio device is Sony WF-100XM3, media player is VLC in OpenSL ES mode. Wavelet is in legacy mode because VLC in AudioTrack mode will fail to load audio while Wavelet is active.

**Comment by sebas05000** [comment]
I have the same issue before it was working fine: 
Phone: Samsung Galaxy Fold 3 with OneUI 4.1(Android 12) March Security Update

![Screenshot_20220412-175018_Wavelet](https://user-images.githubusercontent.com/66391171/163061774-f493859a-6155-4c15-b574-42d05add75db.jpg)
![Screenshot_20220412-175025_Wavelet](https://user-images.githubusercontent.com/66391171/163061776-fc26a676-df70-4ef9-a52b-10a61930e1b4.jpg)

**Comment by Pittvandewitt** [comment]
An issue with these symptoms has been resolved in the april update (22.04). If you still encounter these symptoms, please let me know. Don't forget to mention which session detection mode you use (enhanced, legacy or default).

**Comment by IndefiniteBen** [comment]
Still have the issue "unable to instantiate PresetReverb", but previously it warned for PresetReverb AND Virtualizer effects.

App version 20.04
Default detection mode
Android 12
Pixel 3a
Youtube Music
Sony WF-1000XM4

I tried to force stop and clear cache for Wavelet but when I reopen and start it I get the warning message again. I haven't tried clearing storage for wavelet or rebooting my phone to fix it.

**Comment by squareSphere29** [comment]
Still having the issue "unable to instantiate PresetReverb" when starting any music playback with Musicolet. Equalizer definitely not working.

App version 22.04
Default Detection
Pocophone F1 MIUI 12.0.3
Musicolet

![Screenshot_2022-04-18-20-15-21-663_com pittvandewitt wavelet](https://user-images.githubusercontent.com/18124696/163807140-e8146261-e9e2-4e5f-9ca0-6f8d7b72ddfc.jpg)

**Comment by mgt1309** [comment]
> An issue with these symptoms has been resolved in the april update (22.04). If you still encounter these symptoms, please let me know. Don't forget to mention which session detection mode you use (enhanced, legacy or default).

samsung A20 5G android 10 paid version official unable to instantiate, presetreverb, virtualizer, and graphic equalizer effects? worked before i decided to upgrade to unlock the features now my audio is coming out crackled and popped with the error message appearing every 2 minutes. I have built in android equalizer and adaptive sound disabled as well as dolby atmos gaming effects off wavelet version 22.04

**Comment by machtoners** [comment]
I'm having the same error on OP Nord, tried app cache clear but error persists

**Comment by drbeat** [comment]
Same issue on Samsung S21 FE.
Works for a while after installing but then stops working with "unable to initialize PresetReverb"

**Comment by chandev2006** [comment]
Hi,

I'm using the wavelet Pro version. I use regular mode but it doesn't change eq settings sometime. Then I enabled enhanced listening it gives me a slight chirp or a cracking sound while opening a music track. And legacy mode  doesn't sound good.

My device is samsung A52 running android 13 and one ui 5.1 and I'm using apple music for music streaming

**Comment by pfr-dev** [comment]
This just started happening for me... What gives?
