### ISSUE TITLE
[Feature request]: Crossfeed

### ISSUE THREAD

**Issue by nocotool** [Pittvandewitt/Wavelet#144]
A crossfeed setting would be a great complement for a headphone app.

**Comment by Pittvandewitt** [comment]
This feature is only possible to implement in local music players and not in global equalizer applications like Wavelet unfortunately.

**Comment by nocotool** [comment]
I'm not sure, but have you perhaps confused crossfeed with crossfade?

What I meant is a crossfeed which makes listening on headphones less tiring. I don't know why this couldn't be implemented. 

https://en.m.wikipedia.org/wiki/Crossfeed

**Comment by Pittvandewitt** [comment]
Wavelet makes use of system libraries for the audio effects. Using those system libraries is required for global equalizer applications like Wavelet. Unfortunately none if those libraries come with a crossfeed functionality.
