### ISSUE TITLE
[Feature Request] Haptic Generator

### ISSUE THREAD

**Issue by Jolanrensen** [Pittvandewitt/Wavelet#145]
On Android 12 and on select devices (Pixel 4/6 and maybe more) it's possible to let the vibration motor play along with the music. https://developer.android.com/reference/android/media/audiofx/HapticGenerator
It's possible to implement this in any equalizer app but since you have done some tremendous work in adding support for this many apps, I think it would be a cool feature to try out. What do you think?

**Comment by Pittvandewitt** [comment]
I did create a version for testing but unfortunately this library is really misbehaving. One thing I noticed is when disabling the effect it simply keeps on vibrating very softly. Another issue is that every first time the effect does not get applied.
I love the idea but it's simply not stable.

**Comment by fillwithjoy1** [comment]
Has the stability of the library improved now?

**Comment by Pittvandewitt** [comment]
> Has the stability of the library improved now?

I checked but it's still not where I can call it useful. For example, the effect dies when any other form of haptic feedback happens. For example through system gestures. And when it dies, you need to manually disable and reenable the effect hoping it will work again, which it often doesn't.

**Comment by fillwithjoy1** [comment]
> > Has the stability of the library improved now?
> 
> I checked but it's still not where I can call it useful. For example, the effect dies when any other form of haptic feedback happens. For example through system gestures. And when it dies, you need to manually disable and reenable the effect hoping it will work again, which it often doesn't.

Yep, I experienced this when testing this myself. It's really frustrating because it doesn't tell you when the haptic effect has turned off on the device. Also I've experienced it being out of sync with the audio (unless you have a super dumbed down project)

**Comment by fillwithjoy1** [comment]
Thought I might ask, has HapticGenerator API been working for anyone? Been sitting in 240705 AP1A amd it's been broken here. Has anyone got it working since 15?
