### ISSUE TITLE
[Feature Request] Flip L/R channels

### ISSUE THREAD

**Issue by Jolanrensen** [Pittvandewitt/Wavelet#146]
One feature that I cannot seem to find anywhere on Android is the ability to flip the audio channels. 
Why would you want that you ask?
Well, in the ASMR community on YouTube there are almost always stereo microphones in use. However, it happens from time to time that the channels are the wrong way around. Then you see something happening on the left side of the screen but you hear it on the right. A simple switch in Wavelet would be awesome for this.
Let me know what you think!

**Comment by Pittvandewitt** [comment]
Sounds like a good idea. Unfortunately this feature is only possible to implement in local music players and not in global equalizer applications like Wavelet.
