### ISSUE TITLE
Wavelet unable to instantiate

### ISSUE THREAD

**Issue by Jawahar75** [Pittvandewitt/Wavelet#156]
I recently purchased wavelet pro version,but everytime I launch it I get a pop up saying unable to instantiate... please look into it.
![Screenshot_20220221-095149_Wavelet](https://user-images.githubusercontent.com/100109548/154888713-fd60fbd0-5cc3-4225-9701-3e8b31d29966.jpg)

**Comment by Pittvandewitt** [comment]
Duplicate of #143
