### ISSUE TITLE
Plex, plexamp & emby

### ISSUE THREAD

**Issue by thisisawesome1994** [Pittvandewitt/Wavelet#16]
Hi.

Are the apps: Plex, Plexamp, Emby, Qobuz
supported?

I don't see any change in your app when using Plexamp! Or is the equaliser automatic without any feedback in your app?

Hope it is supported though.

**Comment by Pittvandewitt** [comment]
It's the other way around actually. The apps you mention can opt in to allow processing of their audio streams by sending these broadcast: [ACTION_OPEN_AUDIO_EFFECT_CONTROL_SESSION](https://developer.android.com/reference/android/media/audiofx/AudioEffect#ACTION_OPEN_AUDIO_EFFECT_CONTROL_SESSION) and 
[ACTION_CLOSE_AUDIO_EFFECT_CONTROL_SESSION](https://developer.android.com/reference/android/media/audiofx/AudioEffect#ACTION_CLOSE_AUDIO_EFFECT_CONTROL_SESSION)

Alternatively can try if legacy mode works on your device.
