### ISSUE TITLE
[Feature Request] Live pitch shifter

### ISSUE THREAD

**Issue by TotalChris** [Pittvandewitt/Wavelet#161]
I like to tune up and down songs sometimes to see how they sound in different keys or to create a different mood. V4A never had this but it's something I know I've seen implemented before on Android somewhere. If this feature gets added, I'll buy the unlock on the Play Store.

**Comment by Pittvandewitt** [comment]
https://github.com/Pittvandewitt/Wavelet/issues/146#issuecomment-1030837139
