### ISSUE TITLE
Android Auto detection or disable

### ISSUE THREAD

**Issue by Rochey** [Pittvandewitt/Wavelet#166]
I'm using Wavelet with some headphones and with my phone speaker and these all work fantastically. 
The headphones are AutoEQ with a little Graphic Equalizer bass boost and the phone speaker is using a Graphic Equalizer personal profile setup with some guidance I found on Reddit. 

The issue I have is that if I leave Wavelet on all the above work fine but when I connect to my Android Auto the Graphic Equalizer settings used for my phone speaker is being used (I think it's this and not the headphones bass boast). Due to the Graphic Equalizer being used my Car speakers sound like everything is distorted and over driven. I have to remember to unlock my phone and disable Wavelet. Then the issue is that when I use my phone later I have to then enable Wavelet to work with the headphones or phone speaker.
Is there any way to detect Android Auto and use another Wavelet profile?
Or if not, is there any way to disable Wavelet when Android Auto is used and then enable Wavelet when it's finished?

Thanks for this software and keep up the great work. It amazes every time me how much better my headphones and phone speaker sound when using Wavelet.

**Comment by Pittvandewitt** [comment]
Resolved in the open beta update.
