### ISSUE TITLE
[Feature Request] Greater EQ Range

### ISSUE THREAD

**Issue by mindplay-dk** [Pittvandewitt/Wavelet#168]
I bought a pair of Sony WH-CH710N headphones - the EQ curve on these is the weirdest I've ever heard, with so much bass I could hardly make out the mids and highs at all... Which lead me to find your app. 🙂

The app has a built-in profile specifically for these headphones - with this, I personally found the lows to be still way to exaggerated and nowhere near a normal, enjoyable music experience.

Even using the custom EQ, with low EQs all the way down, and high/mid EQs all the way up, the bass is still too loud for comfort. (I listen to techno and drum'n'bass, so I honestly don't know who they designed this profile for, ha ha.)

Is there any chance you would consider increasing the range of the EQs?

Perhaps behind an option, so it doesn't affect people with non-crazy headphones.

Most likely, an option for this would require you to also lower the overall volume, when enabled? To avoid distortion.

I guess no one would enable this option unless they have a pair of problematic headphones, so it might not be that big a deal. Although it's not unlikely someone with a wimpy pair of earbuds might attempt to use this feature for extreme bass boost, which probably wouldn't work very well. At some point, there is simply no dynamic range left for anything other than bass. But in my case, I need to turn it down, so it shouldn't be a problem. It might should come with a warning, heh.

What do you think?

Either way, thanks for this app - at least my headphones are not totally unusable with this. 🙂

**Comment by mindplay-dk** [comment]
For reference, here is the crazy EQ profile I'm using now:

![Screenshot_20220421-124233](https://user-images.githubusercontent.com/103348/164441920-181d3574-95bf-4a5f-8f2b-d5d279445fb6.png)

**Comment by Pittvandewitt** [comment]
I would rather suggest checking out how to [import a custom profile:](https://pittvandewitt.github.io/Wavelet/Import). You can experiment with targets and adjust the bass to your liking. The range you can use is much higher than the one in the graphic equalizer

**Comment by Grooves1210** [comment]
`The range you can use is much higher than the one in the graphic equalizer`
@Pittvandewitt What are the maximum boost and cut allowed?  thanks

**Comment by Pittvandewitt** [comment]
> `The range you can use is much higher than the one in the graphic equalizer` @Pittvandewitt What are the maximum boost and cut allowed? thanks

There is no real limit, but keep in mind that clipping will occur if you boost too much. The automatic post-gain setting in the limiter will correct this clipping for you.
