### ISSUE TITLE
Feature question @@

### ISSUE THREAD

**Issue by Doliliserrr** [Pittvandewitt/Wavelet#169]
May I ask what is the real use of the "Enhanced session detection" feature? I still don't understand its use @@ I'm not a person with much knowledge about this so i still don't understand @@ please someone explain in a simple and understandable way and that function is real necessity or not? Tysm ❤

**Comment by Pittvandewitt** [comment]
Most music players let know when audio playback is occuring. But YouTube for example does not let the Android system know it is playing audio. The permissions needed for the enhanced session detection mode can be enabled so Wavelet can find more audio sessions, including those of YouTube. Audio sessions must be discovered by Wavelet before audio effects can be applied to them.
