### ISSUE TITLE
Auto EQ keeps disappearing and reappering

### ISSUE THREAD

**Issue by Visualatory** [Pittvandewitt/Wavelet#171]
Hello! (first GitHub post :p)
On my phone I usually use the Auto EQ on Wavelet, which for some reason, keeps reappearing, but straight after disappearing shortly after opening the app again? Is it because it's not supported?
It usually works..

device info if needed:
ASUS 5Z (not rooted)
Android 10
Version 22.04
Sony WH-H900N

**Comment by mzsf** [comment]
Did you resolve this issue? I just installed wavelet but don't see the option for AutoEQ - only the graphic equalizer. I have this issue for both enhanced session detection and legacy mode
![Screenshot_20220618-134546 (1)](https://user-images.githubusercontent.com/36120171/174456579-d8f32a61-bce8-4e76-8db4-b5a2fc2d9334.png)

**Comment by Pittvandewitt** [comment]
Features are displayed dynamically. Connect your headphones and AutoEq will appear. Your configuration will also be saved and restored based on the connected device.
