### ISSUE TITLE
Music Session not detected automatically

### ISSUE THREAD

**Issue by trip6kitty** [Pittvandewitt/Wavelet#173]
I'm on Android 13 beta 2. I've noticed on Android 13 beta 1 and 2 that music sessions are not detected. I have enhanced detection turned on via both permissions granted. 

However it does work via Legacy Mode.

I am able to assist further for testing if needed. Not sure if this is a bug with A13 or I'm doing something wrong.

**Comment by selvakk2k** [comment]
It's probably something to do with android 13 as I have exactly the same issue. I thought it might have got borked while updating but a reinstall doesn't change things. 

I'd like to put my hat in if any testing is required.

**Comment by Pittvandewitt** [comment]
Thank you for the report. It seems that the format of the information returned by the audio dump has changed a little in Android 13. If this is the only thing that has changed, it should be quite an easy thing fix.

**Comment by trip6kitty** [comment]
Awesome! Thanks for the great app. I use it everyday.

**Comment by Pittvandewitt** [comment]
Resolved in the open beta version.

**Comment by trip6kitty** [comment]
Confirmed with the latest update that the issues gone.

Thanks again!
