### ISSUE TITLE
QuickSettings tile to toggle EQ

### ISSUE THREAD

**Issue by Netherquark** [Pittvandewitt/Wavelet#175]
A QS tile to toggle EQ would greatly improve convenience while listening to music

**Comment by Akusimr** [comment]
@ # #165

**Comment by Akusimr** [comment]
Duplicate of #

**Comment by Netherquark** [comment]
my bad

**Comment by Akusimr** [comment]
[https://github.com/Pittvandewitt/Wavelet/issues/175#issue-1253436730]()

**Comment by Pittvandewitt** [comment]
Implemented in version 23.12
