### ISSUE TITLE
Add MPGO to supported players 

### ISSUE THREAD

**Issue by enricocid** [Pittvandewitt/Wavelet#176]
It seems to be working very good with mpgo (legacy mode) but don't know if it requires additional settings (or i would have send a PR)

https://github.com/enricocid/Music-Player-GO

**Comment by Pittvandewitt** [comment]
I'll happily include your music player if your player broadcasts its audio session. This is needed for Wavelet to attach audio effects per app.
Legacy mode processes the global audio session and does not work on many devices.
Please refer to [this comment](https://github.com/Pittvandewitt/Wavelet/issues/32#issuecomment-691476597) for instructions

**Comment by enricocid** [comment]
Should be fixed now :)

<p align="center">
<img width="400" src="https://user-images.githubusercontent.com/7274841/192535303-8be4052e-6150-4dd3-8a79-3440ccfc53e3.jpg">
</p>

**Comment by Pittvandewitt** [comment]
MPGO is added to the list. Congratulations on the nice app.
