### ISSUE TITLE
[Feature Request] Profile Binding for BT Devices

### ISSUE THREAD

**Issue by gsymeoni** [Pittvandewitt/Wavelet#177]
Device-specific profile binding for different connected bluetooth devices. In many cases profile switching is forgotten, leading to confusion with bad sound quality. Probably limited to Bluetooth devices that can report their identity for binding.

**Comment by Pittvandewitt** [comment]
This is already implemented since day 1. You must be experiencing [this issue](https://issuetracker.google.com/issues/204224261), which is a bug some vendors have in their system.
