### ISSUE TITLE
[Feature] Bluetooth Profiles 

### ISSUE THREAD

**Issue by isXander** [Pittvandewitt/Wavelet#187]
At the moment, no matter what headphones I connect, it will have the previous configuration with the other headphones auto EQ etc. 

It would be cool if you could have multiple profiles, depending on which device is currently playing audio.

**Comment by Pittvandewitt** [comment]
This is already supported in Wavelet, but some OEMs suffer from a bug that causes the behavior you experience. I am unable to fix their issues.

**Comment by isXander** [comment]
OK, I'm going to extend my suggestion to make this behaviour visible to the user, displaying some sort of text saying which bluetooth device they are configuring.

Also, be able to configure paired devices when they aren't connected, or playing music would be very helpful.
