### ISSUE TITLE
Wavelet isn't showing AutoEQ on Samsung Galaxy S10+

### ISSUE THREAD

**Issue by ghost** [Pittvandewitt/Wavelet#196]
I don't know why because bofore it was showing but I uninstalled it and when I installed it back it wasn't showing anymore.

**Comment by LegendaryXboi** [comment]
![Screenshot_20220822-080151_Wavelet](https://user-images.githubusercontent.com/63269102/185955623-ff28ee23-78c8-419a-8315-0fe72d504c09.jpg)

**Comment by Mirage1337** [comment]
I am having the same issue on Pixel 6 Pro. Tried with Android 12 and Android 13, same problem.

**Comment by ADubhlaoich** [comment]
Running into an identical issue; Nokia G50 on Android 12.

**Comment by Pittvandewitt** [comment]
Connect your headphones. More options will be available if you do.
This logic also takes care of saving and restoring your configuration based on the connected output device.
