### ISSUE TITLE
Autoeq GraphicEQ import does not import data even though it's supposedly successful

### ISSUE THREAD

**Issue by teddante** [Pittvandewitt/Wavelet#20]
![Screenshot_2020-06-16-17-33-21-761_com pittvandewitt wavelet](https://user-images.githubusercontent.com/37670093/84801778-83b9db80-aff7-11ea-870b-505a8ac44662.jpg)

**Comment by Pittvandewitt** [comment]
Did you search for the imported file by pressing the search icon in the Headphone model dialog? You should be able to find and select it there.

**Comment by teddante** [comment]
Oh I see, it imports it into the list, thanks for the help!
