### ISSUE TITLE
[question] [documentation] Graphic equalizer info

### ISSUE THREAD

**Issue by Hark02** [Pittvandewitt/Wavelet#202]
1) what is the type of filters in graphic EQ (peak filter?)
2) what is the Q value of the filters (if applicable) (1.41?)

**Comment by Pittvandewitt** [comment]
You can imagine the current implementation to use a series of low pass filter with quite a high quality factor. You can read more here: https://developer.android.com/reference/android/media/audiofx/DynamicsProcessing.EqBand#EqBand(boolean,%20float,%20float)

However I am preparing a release that will change this implementation. The next implementation will use many sub bands that are calculated using interpolation.
