### ISSUE TITLE
[Feature Request] Add Support for DAC Hardware Volume Control

### ISSUE THREAD

**Issue by PrinceSangwan** [Pittvandewitt/Wavelet#203]
I am not sure if this is a appropriate request or not, but this is only place and you are the only guy who can fulfill this dream of mine. Some DAC's (such as Apple USB-C to 3.5mm Adapter) don't produce full volume on Android. To fix this, we have to use third party apps such as USB Audio Player Pro (UAPP) or Hiby Music which can control Hardware Volume letting us set it back to its max. The only issue is it's a manual process. I request you to pleasee include this in Wavelet and make this process automatic.

**Comment by ehabheikal** [comment]
You can use the equalizer for this just move all frequencies the same amount up or down.

**Comment by PrinceSangwan** [comment]
> You can use the equalizer for this just move all frequencies the same amount up or down.

I am sorry but that doesn't work. Android somehow limits the hardware volume to 50% on this apple adapter.

**Comment by Pittvandewitt** [comment]
I've taken this into consideration but the way apps like Hiby, UAPP and Neutron achieve this is by implementing a custom USB driver. This means that such a feature would only work in the app playing back audio.
Wavelet does not play back audio as a system wide equalizer, making it impossible to introduce such a feature.
