### ISSUE TITLE
AutoEQ for Anker Q35

### ISSUE THREAD

**Issue by Platinum7765** [Pittvandewitt/Wavelet#205]
Is Wavelet's AutoEQ for Anker Q35 is for ANC mode, or normal mode(ANC off)?

I want to know this because Anker Q35's sound in ANC mode and normal mode are quite different, especially on bass.

**Comment by Pittvandewitt** [comment]
This is the source of the measurement used https://www.rtings.com/headphones/reviews/anker/soundcore-life-q35-wireless
It is measured with ANC on.

Next update will include nwe results from oratory1990, which contains data for wired mode and anc on and off.
