### ISSUE TITLE
clipping issues on YouTube video and Instagram

### ISSUE THREAD

**Issue by imronsaputra11** [Pittvandewitt/Wavelet#207]
i heard this clipping noise when play YouTube video and Instagram, when low frequency hit, the noise appier, i tried max out the buffer size but it didn't help, Wavelet version 22.07, Android 11

edit: i experience this clipping noise only happened at bluetooth connection

**Comment by Pittvandewitt** [comment]
The automatic post-gain option in the limiter settings fixes this.
