### ISSUE TITLE
Android 7 support?

### ISSUE THREAD

**Issue by dittodhole** [Pittvandewitt/Wavelet#21]
Hi there!

Is there any chance to support Android 7?
Reason for asking: I am using [Fiio M11](https://www.fiio.com/m11) as my playback device, which is on Android 7, and I'd like to tune my DT 770 accordingly with Wavelet, as it is mentioned as [**the** go-to solution for Android](https://github.com/jaakkopasanen/AutoEq#android).

Best
Andreas

**Comment by Pittvandewitt** [comment]
Hi,
Wavelet depends on system libraries introduced in Android 9. Therefore it's not possible to support older versions of Android.
If you manage to root your device, you can try and install ViPER4Android or JamesDSP and use a convolution file to achieve a similar result.
To root your device you can download the firmware here http://fiio.me/forum.php?mod=viewthread&tid=44290, grab the boot image and patch it with Magisk manager.

https://forum.xda-developers.com/android/apps-games/app-viper4android-fx-2-6-0-0-t3774651
https://forum.xda-developers.com/android/apps-games/app-reformed-dsp-manager-t3607970

**Comment by dittodhole** [comment]
Hi, thanks for clarification (and taking the time to investigate on the rooting part 👍 )!
