### ISSUE TITLE
[Feature] loudness Correction

### ISSUE THREAD

**Issue by aspidxt** [Pittvandewitt/Wavelet#212]
Problem: Human hearing threshold depends on frequency and it's not linear:
![image](https://user-images.githubusercontent.com/29504662/201548130-a877c6ae-18eb-48de-be30-6bbecab8efd0.png)
So when we decrease volume we hear less base (according to graphic above)

So it's possible to correct this with equalization, so we can listen music "freqency consistantl" on any volume level. It's implemented greatly with internal plugin of EqualizerAPO (Windows)
Here is source of this plugin in EqualizerAPO repo:
https://sourceforge.net/p/equalizerapo/code/HEAD/tree/trunk/filters/loudnessCorrection/

It's will be awesome to have this feature in Wavelet.
It's kind of already possible, just bind AutoEQ intensity level to system volume level)) but it's better to have another effect in list)

Thanks!

**Comment by aspidxt** [comment]
I'm recommending to check this feature in EqualizerAPO, if you on Windows, it's geatly improve listening experience for me.

**Comment by Pittvandewitt** [comment]
Thank you for the suggestion. I have been working on this some time ago but it never got finalized. I'll give it another shot.

**Comment by aspidxt** [comment]
Awesome! Thanks, please let me know if I can help in some way.

**Comment by aspidxt** [comment]
Implemented in v 23.11
Works as expected. Thanks!!!

**Comment by Pittvandewitt** [comment]
It took some time, but here we are!
