### ISSUE TITLE
Ensuring my app is detectable by Wavelet?

### ISSUE THREAD

**Issue by har-nick** [Pittvandewitt/Wavelet#213]
Hey there! Big fan of the app!

I'm currently working on a music player app, and I'd like to make sure it can be detected by Wavelet.

I checked the wiki, which mentioned a "broadcast". The only thing I can imagine would be related is ` android:exported ` in an app's manifest file.

Can I ask how to make sure Wavelet can see my app? I'm using ExoPlayer, if that's of any significance.

Thanks!

**Comment by Pittvandewitt** [comment]
Hello,

Does the information provided [here ](https://github.com/Pittvandewitt/Wavelet/issues/32#issuecomment-691476597) suffice?

**Comment by har-nick** [comment]
Brilliant! Thank you!
