### ISSUE TITLE
"Apps using Wavelet" list keeps adding same app over and over

### ISSUE THREAD

**Issue by carlylemiii** [Pittvandewitt/Wavelet#22]
The app name never leaves the notification, and it just keeps adding the app.

STR:

1. Open Wavelet
2. Open and play Apple Music
3. App name shows in notification, which is great
4. Clear Apple Music from recents
5. Notification still says Apple Music connected
6. Open and play Apple Music again
7. Apple Music is ADDED to list

![Screenshot_20200617-153444](https://user-images.githubusercontent.com/29067983/84947857-904e3a80-b0b0-11ea-832f-4e216107876e.png)

**Comment by Pittvandewitt** [comment]
Apple music clearly doesn't close audio sessions properly. This is a bug in Apple music and not in Wavelet.

**Comment by carlylemiii** [comment]
Shouldn't the app still recognize that Apple Music is Apple Music is Apple Music and not list the same app repeatedly? Even if it doesn't ever _clear_ because of an Apple bug?

**Comment by carlylemiii** [comment]
Also happens with Google's own YT Music.

**Comment by Pittvandewitt** [comment]
It is possible that an app has multiple active audio sessions. If effects are released from a session that is still open when the same app opens a new session, control will be lost. It is not possible to regain control if the old session is reused. This may introduce unexpected behaviour.

You are right about YT Music. Deezer is also plagued with this bug, but worse. It is staggering how many applications have incorrectly implemented session broadcasting. I guess reading the documentation is hard, even for developers working for Google, Deezer and Apple: https://developer.android.com/reference/android/media/audiofx/AudioEffect#ACTION_CLOSE_AUDIO_EFFECT_CONTROL_SESSION

**Comment by carlylemiii** [comment]
Thank you for the link. I will include it when I submit bug report to Apple.

As far as regaining the session, I didn't mean that -- I meant fixing things from a purely visual standpoint, so the notification doesn't pile up the same app. Does the notification already show app x? Then don't show app x again, in other words.

**Comment by Pittvandewitt** [comment]
I'm willing to change it to something like 'Apple Music (3x)' to make the notification less cluttered. It is good to know the size of the list. If there are too many sessions open and let's say changing a single setting takes 50ms to apply, it will take 400ms to update when there are 8 sessions are open.

**Comment by Pittvandewitt** [comment]
This has been implemented in the version I just pushed to the Play Store. It will be available in a few hours.
