### ISSUE TITLE
Legacy mode stopped working on Pixel 6 after firmware update

### ISSUE THREAD

**Issue by yakdmt** [Pittvandewitt/Wavelet#220]
Hi! First of all: thank you for the app, it's great! 
Recently my Pixel 6 got a firmware [https://support.google.com/pixelphone/thread/191508547/google-pixel-update-december-2022?hl=en](update) and I realized that the app is no longer support legacy mode for LDAC Bluetooth connection (I use Sony WH-1000XM4). Why is this important: without legacy mode I have chopping (or popping) sound in all apps (I tried Spotify, Apple Music, AIMP), even with maximum buffer size. The problem existed only for LDAC connection, with SBC or AAC - no audio issues. Is there any chance to fix it? I can get any debug info you need. Thanks in advance!

UPD: all permissions are granted and adaptive sound is off

**Comment by bedoornbos** [comment]
I am also having problems with legacy mode on my Pixel 7 Pro which is on the latest firmware

**Comment by thorgod949** [comment]
Pixel 7 Pro here with shell commands active. I did not try before the December update but, rn for sure it is not working in standard mode or legacy.

I disabled the new adaptive audio, rebooted it, and it still does not work. Pm me if you need any dumps or data to solve

**Comment by dictvm** [comment]
Can confirm that Wavelet currently fails to apply any effects on the latest Android 13 on my Pixel 7 Pro.

Let me know if I can help debug this.

**Comment by jcarletto27** [comment]
I was dealing with this issue and tried everything. It seems like Legacy mode doesn't play nice when you have "Disable Bluetooth A2DP hardware offload" enabled. Once I turned that feature back off, legacy mode began to work as expected.
