### ISSUE TITLE
Exclusive USB audio access

### ISSUE THREAD

**Issue by GuihongWang** [Pittvandewitt/Wavelet#226]

**Comment by dhelgerson** [comment]
No information given but judging by the title, this would be an awesome feature. Bypassing Android's crap audio engine would be great as well as getting around the issues some DACs have such as apple's dongle.

**Comment by Pittvandewitt** [comment]
While this sound all cool and stuff, the Android audio engine is what makes Wavelet possible. Bypassing it will also mean Wavelet won't be able to work.
