### ISSUE TITLE
Wavelet Android apk is detected as having a Trojan 

### ISSUE THREAD

**Issue by wallali** [Pittvandewitt/Wavelet#228]
Developers please note that Avast antivirus is picking up this as having a trojan.

Avast-Mobile Android:Evo-gen[Trj]

Installed from Google Play store

**Comment by Pittvandewitt** [comment]
Thank you for the heads up. I am 100% sure this is a false positive. All libraries used are open source (apart from the official google play billing library) and from trusted sources.
The only possibility I can think of is that their algorithm is getting triggered on the anti piracy measures I wrote to prevent some basic attacks from happening, which I find quite ironic.

I was able to reproduce your case, but I am no longer. I hope they received my report about the false positive and took responsibility for it. It's quite disgusting that a 3rd party app can screw over other apps like mine just like that.

**Comment by wallali** [comment]
Hi,
thanks for looking into it. It can be frustrating when a false positive is picked up, but then again perhaps an opportunity to improve the build pipeline would be to maybe auto-scan the built binary against an antivirus dB. That way it picks up such an issue before release and can be investigated.

**Comment by Mushious** [comment]
Hi,

Posting this in this thread as it's a similar issue, can create a new issue case if you prefer. 

As of 24/07/23, Oppo's built in antivirus is flagging Wavelet as malicious, not sure what is happening to trigger this. (Phone model Oppo Find X3 Pro, Android 13)

![Screenshot_2023-07-24-06-45-41-83_035d55d4552197c94b0185899d8a326c](https://github.com/Pittvandewitt/Wavelet/assets/140355797/840d9474-4243-468c-aff0-b7466e334ff1)

**Comment by Pittvandewitt** [comment]
Thank you for your report. If you downloaded Wavelet from the Play Store I can assure there is no virus or trojan included. Not in the code I wrote nor in the external libraries used.
The warning is triggered by measurements taken to make it harder to create cracked versions of the app.
