### ISSUE TITLE
Disable Autofill in headphone search field

### ISSUE THREAD

**Issue by carlylemiii** [Pittvandewitt/Wavelet#23]
![Screenshot_20200620-191338](https://user-images.githubusercontent.com/29067983/85213956-d4e50a80-b32a-11ea-9b9d-7c6f4597eece.png)

**Comment by Pittvandewitt** [comment]
Isn't that just a context menu provided by 1Password? I'm not sure what you're asking.

**Comment by carlylemiii** [comment]
It's a request for marking the field as not important for Autofill so the Autofill API doesn't kick in in this field.

https://developer.android.com/guide/topics/text/autofill-optimize#important

**Comment by Pittvandewitt** [comment]
Alright that makes sense. I will include it in the next update.
