### ISSUE TITLE
Paid Version Does Not Appear in New Phone

### ISSUE THREAD

**Issue by malardev** [Pittvandewitt/Wavelet#232]
I paid the one time fee via Google Playstore in December 2022. I just changed by phone and when I reloaded the full version does not appear. My playstore account details are unchanged. It even shows the purchase made in December 2022. I tried deleting and reinstalling but the full version does not work. Please advise.

**Comment by Pittvandewitt** [comment]
Try clearing the Play Store data through your system settings. This is where all purchases are stored.
By clearing the data you will fetch all purchases again in case things got corrupted.
Don't forget to reboot your device after.
