### ISSUE TITLE
The app works great. Could we add HRTF?

### ISSUE THREAD

**Issue by sleepin-scotsman** [Pittvandewitt/Wavelet#233]
Years ago, I tried the WavesNX app that used a head-related transfer function so it mimicked listening to stereo speakers in a room instead of listening to headphones. It greatly reduced fatigue when listening to music that contained hard stereo panning. The waves app did not work very well.

I still use WavesNX on my computer, but it automatically adds in reverb with no way to turn it off.

Your app works! I would love to see an HRTF feature added.

**Comment by Pittvandewitt** [comment]
All AutoEq entries contain measurements of headphones. These have been compensated using the harman target. 2019v2 for in ears and the 2018 variant for headphones. These targets already have taken HRTF into account to mimick 'good speakers in a good room'.
This however is where the limit is reached. There is no way I can do head tracking for full HRTF or spatial audio to Wavelet.

https://www.sonarworks.com/blog/learn/the-hidden-flaw-in-hrtf-emulation
https://www.headphonesty.com/2020/04/harman-target-curves-part-1/

**Comment by sleepin-scotsman** [comment]
Hi,

I suppose I should have been more specific. People aren't consistent in what they use "HRTF" to refer to. I understand that AutoEq entries have applied harman target curves.

What I had in mind was HRTF/spatial audio without head tracking--it would really just be crossfeed with phase delay. Even without head tracking, I find that it improves the sound in headphones and reduces fatigue in hard-panned tracks. Since I want to see the feature added, I would be happy to contribute. Let me put together an HRTF model, and you could tell me if it could be integrated into wavelet.
________________________________

**Comment by Pittvandewitt** [comment]
That sounds very much like BS2B. Introducing an effect like that would require root access to install the library with the effect.
Wavelet only uses already existing audio libraries, so it's not possible to introduce HRTF unfortunately.
