### ISSUE TITLE
Reverberation is not changing anything

### ISSUE THREAD

**Issue by Mofankri** [Pittvandewitt/Wavelet#234]
I bought wavelet like a year ago and the reverb did not work or gave any changes. I thought it was due to my poor in ear monitor, although as long as I know even it is not a high-end one, it is still decent. Now after I bought better one, it still does not change anything. Virtualizer and Bass tuner is working just fine tho.

My device:
Samsung galaxy note 10+
Tangzu zetian wu heyday edition (in ear monitor)
DAC dongle Jcally JM20 with CS 43131

I've tried using spotify, apple music, poweramp pro, even built in Samsung music player and nothing affected by reverb. I've set my buffer size to 8192 samples and keep dolby and uhq upscaler off. I have not set the DUMP permission, does it needed?

**Comment by Pittvandewitt** [comment]
Next update will include a possible fix for the issue you experience. I'm planning a release fairly soon.
