### ISSUE TITLE
premium and google accounts 

### ISSUE THREAD

**Issue by ReLiCx404** [Pittvandewitt/Wavelet#235]
I bought wavelet premium and it is connected to my 1st gmail account but when i open the app it gets data from the 2nd gmail account, i can fix this problem by removing the 2nd gmail account and then wavelet recognizes the purchase correctly but not really a viable solution for me

**Comment by Pittvandewitt** [comment]
This really is an issue with the design of how in-app purchases work. There is not much I can do about the situation. Perhaps an update in the Google Play Billing library will improve things in the future.
