### ISSUE TITLE
Add notification button

### ISSUE THREAD

**Issue by Incognito009** [Pittvandewitt/Wavelet#240]
![Screenshot_20230406_103101_One UI Home](https://user-images.githubusercontent.com/76397211/230277078-d54a3b7e-2b0c-4d1d-93e4-640a64be1ecd.jpg)
Add notifications button like above  given img.

**Comment by Pittvandewitt** [comment]
Duplicate of https://github.com/Pittvandewitt/Wavelet/issues/225
