### ISSUE TITLE
[ Feuture Request] polarity inverter and tone generator

### ISSUE THREAD

**Issue by thinkpadL470** [Pittvandewitt/Wavelet#241]
would be really nice to see a button to invert the polarity of both channels since some tws iems come with inverted polarity and there is no way to correct it accept digital. (the difference between inverted and correct polarity is audible on some instruments/bass)
and a tone generator for cheking the eq for peaks/dips

**Comment by Pittvandewitt** [comment]
It is not possible to implement the first feature you request in Wavelet. Also for testing I believe listening to a familiar song is a more valid way of telling if your configuration sounds good to you.
