### ISSUE TITLE
My Graphic EQ has different bands.

### ISSUE THREAD

**Issue by scor2** [Pittvandewitt/Wavelet#243]
Android 13
Galaxy S20+ (SM-G986) / Galaxy Buds 2 Pro (SM-R510)
Wavelet (23.03 / Purchased / DUMP Enabled) / AIMP music player
Other system EQ Disabled (ex : galaxy wearable, dolby, etc)

When I saw official screenshot and other guys screenshot,

their EQ bands are likes this. (75, 150, 300, 600, 1.2K, 2.4K, 4.8K, 9.6K, 19.2K)

But My EQ bands are likes this. (62.5, 125, 250, 500, 1K, 2K, 4K, 6K, 8K, 16K)

https://gall.dcinside.com/mgallery/board/view/?id=galaxy&no=719626
So I can't adjust EQ bands like other guy's Buds 2 Pro recommend setting.

I must adjust 19.2K, but it doesn't shown on my app.

How I can change EQ band like other guys?

**Comment by Pittvandewitt** [comment]
You cannot change it. There was a flaw in previous graphic eq implementation that is now resolved. The band frequency changes now better reflect what you are hearing.
Also why not use the AutoEq configuration?
