### ISSUE TITLE
Auto eq for Realme buds q

### ISSUE THREAD

**Issue by AanooBeta** [Pittvandewitt/Wavelet#247]
I can't find a file related to realme buds q although I'm sure you have heard the name of realme and it's a well known company but still there is no support for it's tws it would be awesome if this app can Support it so I can enjoy being an audiophile thank you so much

**Comment by Pittvandewitt** [comment]
https://pittvandewitt.github.io/Wavelet/Troubleshooting#headphone-model-not-listed-in-autoeq
