### ISSUE TITLE
Unable to make an In-app Purchase

### ISSUE THREAD

**Issue by ankur1674** [Pittvandewitt/Wavelet#25]
Unable to make an In-app Purchase, the play store says transaction declined, tried on multiple user accounts, and asked different people to do it. No one was able to make the purchase.

**Comment by hmnd** [comment]
Came here to report this, as well. Contacted Google Play support and they told me it's something on the seller's end.

**Comment by Pittvandewitt** [comment]
There are some issues regarding verification and the process is slow. I'm doing the best I can to solve it as quickly as possible.

**Comment by Pittvandewitt** [comment]
Problems are resolved now.
