### ISSUE TITLE
[Feature] Allow bass enchantments for internal speaker

### ISSUE THREAD

**Issue by aspidxt** [Pittvandewitt/Wavelet#253]
Please allow bass enchancements for phone speakers as well as for other profiles. Sometimes Wavelet didn't change profile after disconnecting headset, and those setting become available, It helps a little.

Thanks!

**Comment by Pittvandewitt** [comment]
Profiles not switching is a bug, and adding the bass features to the speaker settings is not the intention I have. The device speaker is generally as well tuned as it can be.
