### ISSUE TITLE
Provide an option to purchase/use pro with a degoogled device

### ISSUE THREAD

**Issue by lunaneff** [Pittvandewitt/Wavelet#254]
I run GrapheneOS on my phone, which doesn't come with Google Play. It can however be installed as a regular sandboxed app without special permissions. Because of privacy concerns regarding Google, I run it (and most other proprietary apps) in a work profile. But because Wavelet won't work unless it's installed in a regular user profile, I copied the app over to my work profile, where Play isn't available.

It'd be super useful to both me and many others if you could provide a method to get Pro features on degoogled devices. Maybe have a server storing who has pro (via OAuth)? And then also provide a payment method that doesn't go through Google?

**Comment by Pittvandewitt** [comment]
Sorry but I don't have the time and resources to come up with my own in-app purchase solution. Server maintenance and making sure people are able to access their digital goods at all times is something I'd rather stay away from. Think about payment providers, refunds, caching for offline use etc.
