### ISSUE TITLE
Does not work with live streaming apps

### ISSUE THREAD

**Issue by luisinhobr** [Pittvandewitt/Wavelet#256]
I have been using Wavelet for a while and I really like its features. However, I have noticed that it does not work well with live streaming apps such as Discord, Steam Link, Parsec app and VBAN Receptor. When I use these apps, Wavelet does not apply any effects, it doesn't even acknowledge there's sound coming out. This is very frustrating because I want to apply some EQ while streaming or watching streams. Is there any way to fix this issue or make Wavelet compatible with these apps? Thank you for your attention and support.
![c6178d96-6c32-4641-a95b-4b11294f0990](https://github.com/Pittvandewitt/Wavelet/assets/124622177/4987806c-c804-4e80-9805-d23f5a103961)
![9ed97824-5443-4606-bd9c-3799eafbbaba](https://github.com/Pittvandewitt/Wavelet/assets/124622177/414867f8-a06c-46e9-bf0a-b53bf0b1663e)

**Comment by Pittvandewitt** [comment]
The apps you mention don't have support for external audio processors built in. Try either https://pittvandewitt.github.io/Wavelet/Settings/#legacy-mode or https://pittvandewitt.github.io/Wavelet/Settings/#enhanced-session-detection
