### ISSUE TITLE
AutoEQ Feature not showing

### ISSUE THREAD

**Issue by NightyEve** [Pittvandewitt/Wavelet#258]
Hello,
The AutoEQ feature is not present, i tried legacy mod and bought the pro version but still not there.

I'm on Android 11
Oneplus Nord n10
![Screenshot_20230817-134339](https://github.com/Pittvandewitt/Wavelet/assets/139539603/2cb431dc-1580-4a78-8304-329c592a798e)

**Comment by unoukujou** [comment]
I think you need to plug in headphones for it to show up. That's how it is for me, at least.

**Comment by NightyEve** [comment]
Looks like i needed to signup to the beta in the google store Wavelet app page.
It updated and its now showing
