### ISSUE TITLE
LDAC Support

### ISSUE THREAD

**Issue by hmnd** [Pittvandewitt/Wavelet#26]
When trying to use Wavelet with headphones with LDAC enabled the error `Wavelet was unable to instantiate Virtualizer effects`. This happens on my Sony WH-1000XM3,
![Screenshot_20200711-202444](https://user-images.githubusercontent.com/12853597/87238321-f9765480-c3b5-11ea-8326-5b2c8da86122.png)

**Comment by Pittvandewitt** [comment]
This is a limitation in the virtualization library used. I can not fix this unfortunately.
