### ISSUE TITLE
Error: no permission specified 

### ISSUE THREAD

**Issue by Wind-stormger** [Pittvandewitt/Wavelet#261]
When I try to enhanced session detection, it can't work:

```adb
127|ASUS_AI2201:/ $ pm grant com.pittvandewitt.wavelet                                                                                       
Error: no permission specified
1|ASUS_AI2201:/ $ android.permission.DUMP                                                                                                    
/system/bin/sh: android.permission.DUMP: inaccessible or not found
127|ASUS_AI2201:/ $
``` 
Android 13
Asus ROG Phone 6

**Comment by Wind-stormger** [comment]
How do I give permission? USB debugging has been turned on.

**Comment by Pittvandewitt** [comment]
Try putting everything on one line. It looks like you hit enter before you specified the permission.
Run either
`adb shell pm grant com.pittvandewitt.wavelet android.permission.DUMP`
or
`pm grant com.pittvandewitt.wavelet android.permission.DUMP`

**Comment by Wind-stormger** [comment]
> pm grant com.pittvandewitt.wavelet android.permission.DUMP

Great!!! Many thanks!

💘 💘 💘 💘 💘

**Comment by Wind-stormger** [comment]
> It looks like you hit enter before you specified the permission.

I don't get it mean, I just hit enter key once to run the command.

If you don't mind, I'd like to know what's going on.

**Comment by Wind-stormger** [comment]
![image](https://github.com/Pittvandewitt/Wavelet/assets/76462385/0167220f-1fbf-4416-a7ba-2b34173c8341)

I suddenly understood, because of this automatic line break, I mistakenly thought it was two lines of commands!
