### ISSUE TITLE
Pre-amp addition

### ISSUE THREAD

**Issue by Xorio71** [Pittvandewitt/Wavelet#264]
Hello! I have a feature request for Wavelet, and I'd like to see if it would be possible for you to implement it!

That feature is: pre-amp!

Me, and a whole group of other people experience audio clipping when EQing using your app. I am aware that we can use the channel balance setting to reduce the amplitude of the signal, but that is not ideal, since if this is used as a pre-amp for frequency boosts over 9.9dB (and not only, this is but one example), there's no room for channel correction anymore. There is also the Limiter, but that cannot replace a dedicated pre-amp.

A separate pre-amp setting with a max value of 15dB and a minimum value of -15dB would be ideal, just like Poweramp has. This would leave the whole 9.9dB headroom for channel correction, remove the need for the limiter, and allow easy and simple signal volume attenuation per need.

**Comment by Pittvandewitt** [comment]
A setting for controlling this value automatically will be released fairly soon: https://github.com/Pittvandewitt/Wavelet/commit/080fa9e8f58dd7439d5bd0a135e2662fad58367f

**Comment by Xorio71** [comment]
You are amazing!

**Comment by Xorio71** [comment]
Hi there, once again!

Since there isn't anything concerning this topic on the forum you have
opened on XDA, nor on Reddit, I thought "Why not ask directly the dev?".

I just want to know if there should be any difference between "Legacy Mode"
and "ESD" when it comes to audio quality. Logically there shouldn't be, but
at the same time, I feel like the sound when "ESD" is chosen is more
full-bodied (Which could be entirely placebo).

Thanks in advance!

**Comment by duchieu235** [comment]
Idk how it took this long for someone to ask for a pre-amp option, it should have been on by default
Also when I turn on the channel imbalance option my AutoEQ gets disabled for some reason? Like it doesn't display that AutoEQ is turned off but it's clearly audibly turned off

**Comment by Pittvandewitt** [comment]
> I just want to know if there should be any difference between "Legacy Mode" and "ESD" when it comes to audio quality. 

There is no difference between ESD and default mode when it comes to audio quality. For legacy mode there shouldn't be any difference, but I can't say for sure. Further changes to the output might be applied somewhere else down the stream and it may also be manufacturer dependent.
