### ISSUE TITLE
Subsequent songs in VLC are muted

### ISSUE THREAD

**Issue by glibg10b** [Pittvandewitt/Wavelet#265]
If I start playing a song in VLC (3.5.4), it plays and its audio is processed correctly. If I then switch to another song, VLC goes quiet.

Workarounds:
- Enable Legacy mode (applies after changing song).
- Disable Wavelet (applies after changing song).
- Stop the song, close VLC and wait for it to be erased from memory. Open VLC and play the next song.

DUMP and notification access are both granted. VLC is confugured to use AudioTrack.

Phone: Samsung Galaxy A24
OS: Android 13 (One UI 5.1)

**Comment by Vexper780** [comment]
Yep, I have the same issue.

**Comment by Pittvandewitt** [comment]
Seems to be an issue with VLC. It seems it does not (always) support attaching DynamicsProcessing to its music stream.
I recommend reporting the bug there and including the logs attached: https://wiki.videolan.org/Android_Report_bugs

[vlc_crash_report.txt](https://github.com/Pittvandewitt/Wavelet/files/13348649/vlc_crash_report.txt)

**Comment by mirh** [comment]
Follows to #317
