### ISSUE TITLE
Greyed Out Enhanced Session, Even With Both Permissions Enabled

### ISSUE THREAD

**Issue by Vinccino** [Pittvandewitt/Wavelet#266]
Hello. I'm not sure if this is an issue since this is my first time, but is the Enhanced Session Detection setting supposed to be greyed out even when I already have both permissions? It still says "Both permissions are required" as if I hadn't enabled both.

**Comment by Pittvandewitt** [comment]
The section becomes greyed out if legacy mode is enabled. These 2 modes can't be enabled simultaneously .

**Comment by Vinccino** [comment]
Legacy mode was never on, but on second thought it might be working as intended. To be clear, if enhanced session detection is active, it isn't supposed to say something like "active" or "permission granted" right?
