### ISSUE TITLE
[Feature request] Peak level meter

### ISSUE THREAD

**Issue by exxpomob** [Pittvandewitt/Wavelet#268]
When using EQ, you should turn down the volume to avoid clipping.
It's possible to calculate a precise value to avoid clipping, but then you will have to reduce the volume too much, and it's not really necessary.
Therefore, volume reduction is chosen empirically (reduce volume until you can no longer hear clipping).
It would be nice to add a peak meter for the Wavelet output to determine if clipping is occurring or not and how much you can change the volume.

**Comment by Pittvandewitt** [comment]
The auto post-gain feature in limiter settings does this for you. [Info](https://pittvandewitt.github.io/Wavelet/Features/#limiter)

**Comment by exxpomob** [comment]
@Pittvandewitt, thank you for the clarification. I thought the auto-gain reduces the volume to the limiter threshold, but it turns out that these features are independent of each other.

In this case, could you please explain how the maximum EQ gain is calculated, simply as the maximum deviation of the frequency response (as in Sonarworks products) or by more complex methods?

Also, why is the auto-gain in the limiter? I think a lot of users don't care about the limiter, but absolutely everyone would like to eliminate clipping, so it would make sense to have the auto gain in the most prominent place as a separate processing unit.

**Comment by Pittvandewitt** [comment]
> In this case, could you please explain how the maximum EQ gain is calculated, simply as the maximum deviation of the frequency response (as in Sonarworks products) or by more complex methods?

It is explained on the info page.

> Also, why is the auto-gain in the limiter? I think a lot of users don't care about the limiter, but absolutely everyone would like to eliminate clipping, so it would make sense to have the auto gain in the most prominent place as a separate processing unit.

Because post gain is applied in the limiter stage of the audio processor.
If you don't want to notice the compression effect of the limiter, you can set the threshold to -1db
