### ISSUE TITLE
[Suggestion] Please add an option to disable the app if it's not in use. So it doesn't run in the background when the equalizer is not in use 

### ISSUE THREAD

**Issue by Salman7236** [Pittvandewitt/Wavelet#27]

**Comment by Pittvandewitt** [comment]
If Wavelet is disabled, it won't be possible to attach effects afterwards. This will introduce inconsistent behaviour, so adding an option like this is out of the question.

**Comment by Pittvandewitt** [comment]
Recently I have been working on a feature that caches session IDs, making it possible to enable and disable on demand. The feature will be available in a next update.
