### ISSUE TITLE
Equal Loudness 

### ISSUE THREAD

**Issue by Incognito009** [Pittvandewitt/Wavelet#272]
As of now, there is a new updated version in which the new feature equal loudness is not properly  working , this feature has a lot of bass distortion and the vocal has become less, please update it or remove it.

**Comment by Incognito009** [comment]
> As of now, there is a new updated version in which the new feature equal loudness is not properly working , this feature has a lot of bass distortion and the vocal has become less, please update it or remove it.

**Comment by Pittvandewitt** [comment]
- Which device are you using + which android version and firmware version?
- Can you post a screenshot of the graph in a state where you notice the distortion?

**Comment by Incognito009** [comment]
Samsung A03 

> * Which device are you using + which android version and firmware version?
> * Can you post a screenshot of the graph in a state where you notice the distortion?

Samsung A03

**Comment by Pittvandewitt** [comment]
Please also share a screenshot of the equal loudness graph when you hear distortion

**Comment by Incognito009** [comment]
![Uploading Screenshot_20240106_104247_Wavelet.png…]()

**Comment by Incognito009** [comment]
> Please also share a screenshot of the equal loudness graph when you hear distortion

**Comment by Incognito009** [comment]
![Screenshot_20240106_104247_Wavelet](https://github.com/Pittvandewitt/Wavelet/assets/76397211/969603ee-6939-4df6-9b1a-dcf60d0ed2a0)

**Comment by Pittvandewitt** [comment]
Judging by the graph I don't see a possibility you hear any distortion. Are you sure no other options are enabled?
On a side note, the automatic post-gain option in the limiter automatically calculates the optimal gain value to prevent distortion from occurring.
