### ISSUE TITLE
Legacy mode on Android 14 on Pixel 6 does not work for Bluetooth [edit: specifically for aptx. SBC seems to work fine]]

### ISSUE THREAD

**Issue by Mautomate** [Pittvandewitt/Wavelet#273]
When enabled, legacy mode does not show up when using Bluetooth device. It does show up when using on device audio though (phone speakers), but only for on device audio. The regular version still works with Bluetooth but only for the designated apps. The reason I was using legacy mode was for YouTube and other such apps. Attached are pictures showing differences 
![Screenshot_20240110-162401~2](https://github.com/Pittvandewitt/Wavelet/assets/156262164/44e9c29c-9b2e-4fbd-a92e-02577a59642b)
![Screenshot_20240110-162406~2](https://github.com/Pittvandewitt/Wavelet/assets/156262164/9c75dbb8-db82-4f51-9a6d-e643d6ad92f2)
![Screenshot_20240110-162537~2](https://github.com/Pittvandewitt/Wavelet/assets/156262164/bc6a2434-3960-4b51-b112-e530b6c04943)

**Comment by dknikolov** [comment]
I have the same issue on the Pixel Fold with the B&W P8. Disabling HD audio: Qualcomm aptX" HD audio in the headphones Bluetooth settings worked for me. I guess it's using regular aptX now?

**Comment by Mautomate** [comment]
Holy crap thank you, yeah that fixed the issue. I'm using a pixel 6 (I'm going to edit that in the description because it seems like if you're having the issue on a pixel phone as well then maybe it's related) I'm not sure why having aptX enabled makes it not function. Hopefully a future update will fix this issue, especially because of the latency is worse without using aptX

**Comment by Mautomate** [comment]
Sorry I didn't mean to close the issue

**Comment by jonasfreudig** [comment]
I'm having the same issue on my Pixel 7 Pro with Sony Linkbuds S trying to play via TIDAL.
With Spotify, everything works fine (w/o legacy mode), but TIDAL does not work even in legacy mode.
When I deactivate HD audio (LDAC in this case) it works.

It would be nice to be able to use it with HD audio on!

I tried it with TIDAL and my Bose QuietComfort 35 headphones and there it works even with HD audio on - but they use AAC, not LDAC or aptX.

**Comment by Pittvandewitt** [comment]
Seems to be a known platform issue: https://issuetracker.google.com/issues/261579107

When no effects could be instantiated, the blank screen shows up like you are experiencing. It's not something I can fix unfortunately.
