### ISSUE TITLE
App keeps reverting to free version

### ISSUE THREAD

**Issue by xVilho** [Pittvandewitt/Wavelet#279]
Title. Only way i've found to fix this is to restart the phone, but its getting bit annoying to do it multiple times a day.. 
It is completly random. Could just start listening music and wonder hmm, why it sounds so weird --->going to wavelet app and its free version.

**Comment by Pittvandewitt** [comment]
On your device with Wavelet installed, open this url to the Wavelet listing in the Play Store and press 'Open': https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet

**Comment by xVilho** [comment]
Thanks. That fixes it for now. Ill let update here if it still keeps reverting.
