### ISSUE TITLE
attempting to uninstall crashes package installer

### ISSUE THREAD

**Issue by KaterMcDuck** [Pittvandewitt/Wavelet#280]
As title.  When attempting to uninstall wavelet, package installer immediately crashes with "package installer has stopped" all other apps uninstall just fine. 

Checked running apps, and wavelet is not showing up there. Device reset does not help.   I don't know that much about android to know what else to really try.

**Comment by Pittvandewitt** [comment]
That's strange. There must be some bug with the package installer. I'd try uninstall via ADB using `adb uninstall --user 0 com.pittvandewitt.wavelet`

**Comment by KaterMcDuck** [comment]
It hasn't been fixed yet though

**Comment by Pittvandewitt** [comment]
I'm not able to fix a crash related to the package installer. It's outside of the scope.

**Comment by KaterMcDuck** [comment]
Alright.  I figured it out. Couldn't use PC as I've been working away from home.   But it uninstalls from the google play store page
