### ISSUE TITLE
Why does it automatically lifts every EQ above the line of 0db?

### ISSUE THREAD

**Issue by pityalvarez** [Pittvandewitt/Wavelet#283]
Starts at 20hz -2.6 db and the peak is at 1357hz -0.1 db
why wavelet shows it as it were above the 0db line? I'm 100% sure this is why I hear distortion, and I'm forced to use Automatic option on Limiter.

My EQ
![image](https://github.com/Pittvandewitt/Wavelet/assets/97750378/1e9612b1-3986-4fc3-a77a-b734fd8ce317)
![Screenshot_20240321_152309_Wavelet](https://github.com/Pittvandewitt/Wavelet/assets/97750378/5c8ed569-a067-4895-87ed-1b92b0735b16)
AutoEQ
![Screenshot_20240321_152903_Wavelet](https://github.com/Pittvandewitt/Wavelet/assets/97750378/514a8abd-3742-41df-9b35-445c4c41bc94)

**Comment by Pittvandewitt** [comment]
Everything is averaged at 0dB as one can import a file and boost everything with 100dB theoretically. The automatic post-gain feature in the limiter settings will bring the max gain to 0dB to mitigate distortion. It also takes other settings into account such as the graphic eq and the bass tuner. Set the threshold to -1dB if you're worried about the compression effect of the limiter.
