### ISSUE TITLE
Flat EQ

### ISSUE THREAD

**Issue by korpe1** [Pittvandewitt/Wavelet#289]
This is maybe a very stupid question, but what is the point of "Flat" EQ mode? I mean, it's doesn't do anything, so why it's one of modes of the Graphical Equalizer?

I understand what is a flat frequency response, but the point of EQ is make changes to reach that target (or Harman curve etc). If the EQ is flat, when it doesn't do anything, right?

**Comment by robbnj11** [comment]
My guess is a throwback to a time before the "reset" icon was there. Many other apps I have used have "flat" so you don't have to manually reset all your sliders to start over.

**Comment by Pittvandewitt** [comment]
> My guess is a throwback to a time before the "reset" icon was there. Many other apps I have used have "flat" so you don't have to manually reset all your sliders to start over.

Your guess is correct.
