### ISSUE TITLE
Auto EQ suddenly gone.

### ISSUE THREAD

**Issue by robbnj11** [Pittvandewitt/Wavelet#292]
I installed Wavelet, added Musicplayer GO and managed to create my own EQ curve with REW and EAPO, but now my AutoEQ option has disappeared from my main screen. I only have the graphic EQ option.
I tried uninstalling and reinstalling both, but I still only see the graphic EQ option.

Do I have to purchase the Pro option to be able to Auto EQ my listening experience?

**Comment by robbnj11** [comment]
*UPDATE* I uninstalled, reinstalled and purchased it. It's only the cost of a cup of coffee, so why not?
Not sure if that is why, but Auto EQ is back. Love this app!

**Comment by Pittvandewitt** [comment]
Glad to hear you got things working. AutoEq is available if music is playing and your headphones are connected.
