### ISSUE TITLE
Wavelet not recognizing my wired headphones

### ISSUE THREAD

**Issue by braboobssiere** [Pittvandewitt/Wavelet#296]
I'm having a problem with Wavelet not telling the difference between my two wired headphones. I tried using the Moondrop Chu 2 and Hifiman RE400 (both 3.5mm jacked), but Wavelet just shows "unknown" when I plug them in, and just show the last wired auto-eq profile I used.

does it need any permission to do so? (i may unknowingly disabled some permission/notification)

the Bluetooth headphones doesn't have the problem

**Comment by Pittvandewitt** [comment]
There is only so much I can do to detect wired headphones. The only information I can get is if it uses a 3 pin connector (headphones) or a 4 pin connector (headset). But it showing 'unknown' is not desirable. Can you try the same using the beta test version?
