### ISSUE TITLE
"Wavelet was unable to instantiate DynamicsProcessing effects" 

### ISSUE THREAD

**Issue by mrmcsalad** [Pittvandewitt/Wavelet#3]
I'm using a OnePlus 2 with Android 9 (Lineage OS 16) and I get an error whenever I try to use this app (when starting a music stream from spotify)
This might be due to Lineage OS' built in equaliser, AudioFX but I haven't found a way to disable this. Also the AutoEQ option doesn't show up when I plug in my headphones.

**Comment by Pittvandewitt** [comment]
This message occurs when your ROM does not have the DynamicsProcessing library implemented correctly. This results in the features depending on that library to be hidden. You may want to contact your ROM developer to look into the missing libraries.

**Comment by mrmcsalad** [comment]
Thanks for the response, I'll do that or get another ROM.

**Comment by matthew-black** [comment]
Just wanted to give you a heads-up that I'm experiencing this same error on an unrooted Pixel 2 with Android 10. I feel like the ROM on a Google phone should be alright. Anywho, love the app!

**Comment by calroth** [comment]
For anybody using LineageOS or another custom ROM: ask your developers (nicely) to check whether they have included a commit like this one, except for your device: https://android.googlesource.com/device/google/marlin/+/3a44f94401dc3e87732f900046cc97cd0ddee9c3%5E%21/

Often the DynamicsProcessing library is installed, but needs to be configured using a commit like the above. Especially if your device was running Android 8.0 Oreo and was then upgraded to Android 9.0 Pie or above, when this library was first added.

**Comment by DuZiei** [comment]
I have the same problem .
