### ISSUE TITLE
All devices shown as unknown, not switching between profiles

### ISSUE THREAD

**Issue by arilkuz** [Pittvandewitt/Wavelet#301]
Wavelet is unable distinguish phone speakers and any Bluetooth headphones and therefore doesn't switch between profiles (all devices simply shown as unknown). Clearing data, reinstalling Wavelet, restarting device don't help. 

Device: Google Pixel 7, Android 15 Beta 4.1.
Issue appears since a few months ago.

![Screenshot_20240803-034636](https://github.com/user-attachments/assets/ee5dbbc4-dbc2-4582-a536-d84fe959d4c5)

**Comment by Pittvandewitt** [comment]
Attached is the media router demo apk file (change the extension from .zip to .apk as apk files cannot be uploaded here.)
This app can show all routes which will help me debug the situation.

Could you please send a screenshot of the page found in settings - show system routes when the notification in Wavelet is showing unknown?

[app-debug.zip](https://github.com/user-attachments/files/16530856/app-debug.zip)

**Comment by Pittvandewitt** [comment]
Was the device in the notification shown as 'unknown' when the screenshot was made?

**Comment by arilkuz** [comment]
Yes, it always show unknown since the Android 15 Beta updates, no matter which device I use (more than 3 Bluetooth devices as shown in the screenshot).

**Comment by Pittvandewitt** [comment]
The Bluetooth devices listed are the ones that were paired but not necessarily connected. The screenshot indicates that no devices were connected. Is this correct? Wavelet should be displaying options for the device speaker and showing 'speaker' in the notification the moment the screenshot was taken.

Can you send me another screenshot of the media routing app when a bluetooth device is connected and Wavelet is showing 'unknown' in the notification? I'd appreciate it if you can include the status bar so I can see the bluetooth status icon. You can blur or cut other icons if you feel like.

**Comment by arilkuz** [comment]
Yes, it was indeed used to show speaker when using the phone speaker or the name of the Bluetooth device when connected to one, which is unfortunately not the case anymore after Android 15 Beta updates.

Screenshot attached, this time connected to a Bluetooth device. Wavelet processes the audio but still showing unknown.
![Screenshot_20240813-184505](https://github.com/user-attachments/assets/d69ead30-8833-4145-84bc-a05356c2f169)
![Screenshot_20240813-184332](https://github.com/user-attachments/assets/9253edf6-777a-4628-81cb-e1c6b28b1863)

**Comment by Pittvandewitt** [comment]
Just an update. I installed the latest A15 beta but I wasn't able to reproduce this specific case. But I started rewriting parts of the output device detection logic specifically for A14 and higher to detect which device is selected through the output dialog in the media notification. Hopefully this implementation will resolve the bug you reported. The fix won't be available in the next beta version but in the one after it. I would appreciate it if you keep me posted about this when the beta version is available.

**Comment by Pittvandewitt** [comment]
An update is available now. Please let me know if the issue is resolved for you.

**Comment by arilkuz** [comment]
Hey, the issue was still there with 24.05 after I reflashed the Pixel 7 (so
it was definitely not a faulty Android installation), and later I returned
to Android 14, so I can't give you feedback, whether the issue is resolved
or not in this new version.



Am Di., 15. Okt. 2024 um 10:59 Uhr schrieb Thomas W. <
***@***.***>:
