### ISSUE TITLE
[Feature Request] Custom equal loudness curve

### ISSUE THREAD

**Issue by aldemoth** [Pittvandewitt/Wavelet#302]
Docs page says mids should be more dominant when volume is low but I can barely hear mids with low volume. Equal loudness makes the situation worse. 

I tested it with QCY T5 and Taotronics Soundsurge 60, with only AutoEQ enabled. Both(or my ears) suppress mids when volume is low. It would be nice if I could set a custom equal loudness curve similar to graphic equalizer.

**Comment by Pittvandewitt** [comment]
The docs say mids are more dominant at low volumes if equal loudness is disabled. The curve is a given; it's based on the ISO 226 standard, but you can change the threshold to customize when the effect should kick in. It should be set to where the graph just starts moving when you're listening to your baseline volume.

I know for example that the Google Pixel Buds Pro have a volume equalizer (equal loudness) available. Perhaps this is the case for your iems too and you're applying equal loudness over equal loudness which would explain what you're hearing.

Whatever it may be, I'm not going to deviate from a well backed standard to something made up.
