### ISSUE TITLE
Request: Parametric Equalizer

### ISSUE THREAD

**Issue by Fearmipan** [Pittvandewitt/Wavelet#304]
I love Wavelet!
This is the ONLY ONE! EQ app that use global sound effect (session 0/legacy mode).
It's work with gaming, and almost all player!
I just need PEQ with high and low shelf for better equalizer my headphone.

**Comment by Pittvandewitt** [comment]
Check out https://squig.link/. You can use it to export parametric eq filters and import the result in Wavelet - AutoEq. https://pittvandewitt.github.io/Wavelet/Import/

**Comment by Fearmipan** [comment]
WTF!
It solve my problem!
AutoEq not available with phone speaker, but at least I can enjoy gaming with my headphone!
Thanks you! 👍 👍 👍
