### ISSUE TITLE
Wavelet Was Unable to initiate DynamicProccesing on pixel 9 pro XL

### ISSUE THREAD

**Issue by bbnn12** [Pittvandewitt/Wavelet#305]
just got the new pixel 9, and unfortunately, wavelet isnt working and im getting this error, im assuming its processing as the error message itself is getting cut off, i know its a new device and all so im just bringing it to your attention, if there's anything i can do to help, id be more than willing! 

error: https://imgur.com/a/Mu9B2qU

**Comment by pysklo** [comment]
Can confirm, same issue. I however am rooted and granted permission for the "Enhanced session detection". 

Error: [https://imgur.com/a/dfvqSJI](url)

**Comment by ScienceNerb** [comment]
Having issues with my pixel 9 pro as well. There's no audible difference whether on or off. Not even the brief cut in audio is present when turning on or off. Works on my previous phone just fine with all the exact settings and permissions.

**Comment by Neuropsychologist** [comment]
I sent a message to the dev on xda; but also having pixel 9 issues.  Viper 4 android also does not work currently.  Something changed in pixel 9.  Hopefully, this can be fixed soon.

**Comment by jacbrooks** [comment]
My Pixel 9 Pro XL (not rooted) is having this issue also. I get an error when turning off then back on. 
![Screenshot_20240903-195423](https://github.com/user-attachments/assets/3b0ff1f6-5b0f-481e-8cbb-e67f3c78d444)

**Comment by kw1999** [comment]
Pixel 9 Pro user here. I can confirm that I'm also receiving this error. Hope it can be patched soon. 
![Screenshot_20240905-191808](https://github.com/user-attachments/assets/034a91bd-2fc2-4854-967a-d9c0dc3a2bcc)

**Comment by DrSuSE** [comment]
On my Pixel 9 Pro XL, I am not getting any errors, but Wavelet will only if I start playing music, then turn Wavelet on, then toggle any EQ/effects off and then back on.

**Comment by kw1999** [comment]
> On my Pixel 9 Pro XL, I am not getting any errors, but Wavelet will only work if I start playing music, then turn Wavelet on, then toggle any EQ/effects off and then back on.

I cannot thank you ENOUGH for passing on this solution; it worked for me too! It's hardly ideal, but I'll definitely take it as an interim solution until a native patch for whatever seems to be going on with the latest Pixels. Again, thank you SO much!

**Comment by kw1999** [comment]
> On my Pixel 9 Pro XL, I am not getting any errors, but Wavelet will only work if I start playing music, then turn Wavelet on, then toggle any EQ/effects off and then back on.

Does it only work on one song before having to do the whole process over again for you? That's what's happening for me.

**Comment by bbnn12** [comment]
> Pixel 9 Pro user here. I can confirm that I'm also receiving this error. Hope it can be patched soon. ![Screenshot_20240905-191808](https://private-user-images.githubusercontent.com/180600004/364979143-034a91bd-2fc2-4854-967a-d9c0dc3a2bcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODE3NDIsIm5iZiI6MTcyNTg4MTQ0MiwicGF0aCI6Ii8xODA2MDAwMDQvMzY0OTc5MTQzLTAzNGE5MWJkLTJmYzItNDg1NC05NjdhLWQ5YzBkYzNhMmJjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMTMwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWNiYzNjODUzZTM1YjQzNTJlN2I3ZTBjYTlhZjMwNTg4ZmY0YjE4NDZhMWYxMjRkYjZhYmM2OGZkYWJkNDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kuxlOyJo78erjqYiwu0Ty-Kmcgi0483zM0YPODi8So0)

what music player are you using? im not even getting any options to turn on EQ, are you on a14? or are you on a15 beta?

**Comment by kw1999** [comment]
> > Pixel 9 Pro user here. I can confirm that I'm also receiving this error. Hope it can be patched soon. ![Screenshot_20240905-191808](https://private-user-images.githubusercontent.com/180600004/364979143-034a91bd-2fc2-4854-967a-d9c0dc3a2bcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODE3NDIsIm5iZiI6MTcyNTg4MTQ0MiwicGF0aCI6Ii8xODA2MDAwMDQvMzY0OTc5MTQzLTAzNGE5MWJkLTJmYzItNDg1NC05NjdhLWQ5YzBkYzNhMmJjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMTMwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWNiYzNjODUzZTM1YjQzNTJlN2I3ZTBjYTlhZjMwNTg4ZmY0YjE4NDZhMWYxMjRkYjZhYmM2OGZkYWJkNDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kuxlOyJo78erjqYiwu0Ty-Kmcgi0483zM0YPODi8So0)
> 
> what music player are you using? im not even getting any options to turn on EQ, are you on a14? or are you on a15 beta?

I'm using Apple Music on Android 14 stable, build AD1A.240905.004. I never had a single issue with it on my Pixel 8 Pro but the 9 Pro appears to have upended everything.

**Comment by Pittvandewitt** [comment]
I encourage all of you to [submit a bug report](https://support.google.com/pixelphone/answer/6398243?hl=en) to Google about this.
This is important not just for the Pixel 9, but for all other future devices that have the [AIDL audio HAL](https://source.android.com/docs/core/audio/aidl-implement) implemented.

Make sure to toggle Wavelet off, then on just before submitting the report so that the relevant logs are sent to Google.

In the meantime I'll try to come up with a workaround.

**Comment by jacbrooks** [comment]
Try changing your buffer to 5120. Since changing the buffer size it's working now without doing the disable/enable trick. 
![Screenshot_20240925-134809](https://github.com/user-attachments/assets/a928fb2b-eb50-4c52-bbbe-99ede8bcd80a)

**Comment by DrSuSE** [comment]
> I encourage all of you to [submit a bug report](https://support.google.com/pixelphone/answer/6398243?hl=en) to Google about this. This is important not just for the Pixel 9, but for all other future devices that have the [AIDL audio HAL](https://source.android.com/docs/core/audio/aidl-implement) implemented.
> 
> Make sure to toggle Wavelet off, then on just before submitting the report so that the relevant logs are sent to Google.
> 
> In the meantime I'll try to come up with a workaround.

I use both Wavelet and Poweramp EQ. The PEQ did fix his app for the 9 series. I only mention that in case you guys talk and might share fix methods.

**Comment by bbnn12** [comment]
> Try changing your buffer to 5120. Since changing the buffer size it's working now without doing the disable/enable trick. ![Screenshot_20240925-134809](https://private-user-images.githubusercontent.com/2767600/370834934-a928fb2b-eb50-4c52-bbbe-99ede8bcd80a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDk2MTUsIm5iZiI6MTcyNzQ0OTMxNSwicGF0aCI6Ii8yNzY3NjAwLzM3MDgzNDkzNC1hOTI4ZmIyYi1lYjUwLTRjNTItYmJiZS05OWVkZThiY2Q4MGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTUwMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTU2N2I3ZDhiN2U1NGE5ZThkNjE4MWU2OThkY2ViMWQ5NjQyM2RjZTRjZWUxMjQ3YmI4MmFjZWY4ZmIwZDA4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zIPxghHgbo2ftAwB7T1Ux_YMlf78aELX4ObH8zDT2ew)

![Screenshot_20240927-092720](https://github.com/user-attachments/assets/69d53f4e-62d0-422d-9fa0-6d787e790da7)

unfortunately It still doesn't work for me, Ive still got no options for equalizer and the other stuff

**Comment by jacbrooks** [comment]
> > Try changing your buffer to 5120. Since changing the buffer size it's working now without doing the disable/enable trick. ![Screenshot_20240925-134809](https://private-user-images.githubusercontent.com/2767600/370834934-a928fb2b-eb50-4c52-bbbe-99ede8bcd80a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDk2MTUsIm5iZiI6MTcyNzQ0OTMxNSwicGF0aCI6Ii8yNzY3NjAwLzM3MDgzNDkzNC1hOTI4ZmIyYi1lYjUwLTRjNTItYmJiZS05OWVkZThiY2Q4MGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTUwMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTU2N2I3ZDhiN2U1NGE5ZThkNjE4MWU2OThkY2ViMWQ5NjQyM2RjZTRjZWUxMjQ3YmI4MmFjZWY4ZmIwZDA4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zIPxghHgbo2ftAwB7T1Ux_YMlf78aELX4ObH8zDT2ew)
> 
> ![Screenshot_20240927-092720](https://private-user-images.githubusercontent.com/14913112/371583016-69d53f4e-62d0-422d-9fa0-6d787e790da7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NDc5NTQsIm5iZiI6MTcyNzY0NzY1NCwicGF0aCI6Ii8xNDkxMzExMi8zNzE1ODMwMTYtNjlkNTNmNGUtNjJkMC00MjJkLTlmYTAtNmQ3ODdlNzkwZGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDIyMDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YTc0YjIyOTI0MTQ3MGQyZmJjNzBlMjdmNTljZTE2YmRhODNiYjgwY2FmYjQwZjhmNjBjMTMwMTU4ZTA0MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W7MQ9tZuvVkrYv_5Lt54ToiMGs7hbDBU3F5H-zAIFlA)
> 
> unfortunately It still doesn't work for me, Ive still got no options for equalizer and the other stuff

The buffer size trick did stop for me also. The only known workaround now is to disable/enable while audio is playing. I also noticed you didn't grant dump permission on your install. That can contribute to the app not working.

**Comment by bbnn12** [comment]
> > > Try changing your buffer to 5120. Since changing the buffer size it's working now without doing the disable/enable trick. ![Screenshot_20240925-134809](https://private-user-images.githubusercontent.com/2767600/370834934-a928fb2b-eb50-4c52-bbbe-99ede8bcd80a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDk2MTUsIm5iZiI6MTcyNzQ0OTMxNSwicGF0aCI6Ii8yNzY3NjAwLzM3MDgzNDkzNC1hOTI4ZmIyYi1lYjUwLTRjNTItYmJiZS05OWVkZThiY2Q4MGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTUwMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTU2N2I3ZDhiN2U1NGE5ZThkNjE4MWU2OThkY2ViMWQ5NjQyM2RjZTRjZWUxMjQ3YmI4MmFjZWY4ZmIwZDA4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zIPxghHgbo2ftAwB7T1Ux_YMlf78aELX4ObH8zDT2ew)
> > 
> > 
> > ![Screenshot_20240927-092720](https://private-user-images.githubusercontent.com/14913112/371583016-69d53f4e-62d0-422d-9fa0-6d787e790da7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NDc5NTQsIm5iZiI6MTcyNzY0NzY1NCwicGF0aCI6Ii8xNDkxMzExMi8zNzE1ODMwMTYtNjlkNTNmNGUtNjJkMC00MjJkLTlmYTAtNmQ3ODdlNzkwZGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDIyMDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YTc0YjIyOTI0MTQ3MGQyZmJjNzBlMjdmNTljZTE2YmRhODNiYjgwY2FmYjQwZjhmNjBjMTMwMTU4ZTA0MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W7MQ9tZuvVkrYv_5Lt54ToiMGs7hbDBU3F5H-zAIFlA)
> > unfortunately It still doesn't work for me, Ive still got no options for equalizer and the other stuff
> 
> The buffer size trick did stop for me also. The only known workaround now is to disable/enable while audio is playing. I also noticed you didn't grant dump permission on your install. That can contribute to the app not working.

I mean it was working fine on my 6 pro so I doubt that's it, unless 9s gets a different build of a14 than 6? but for now I've switched to Flow Equalizer, that works for me ATM, although you can go negative on pre-gain which is annoying

**Comment by xmaciek82** [comment]
Same.  REcently received my new Pixel 9 Pro and Wavelet no longer works. Will this be resolved for new Pixel phones?

**Comment by c0r3yz** [comment]
Has there been any update to this? None of the workarounds are working for me on my new Pixel 9 Pro.. Wavelet was great on my Pixel 7 Pro...

**Comment by pysklo** [comment]
The dev said to submit reports to Google.

**Comment by c0r3yz** [comment]
> The dev said to submit reports to Google.

Yeah, I've done that, and I know Google isn't always quick address things like this, especially if the Feedback is the only thing that they are relying on to draw attention to this issue. 

Other EQ apps have reported similar issues, which certainly helps solidify that it's a change made specifically on the Pixel 9 Pro (XL and Fold as well) that's to blame, but those apps are testing fixes with their users already. 

With a lot of the changes that were exclusive to the 9 Pro family going out to all Pixel users soon (October 15th), I would think there should be a little more urgency and communication on the progress, if any, especially for users that paid for the Pro version.

**Comment by Neuropsychologist** [comment]
Wanted to follow up on this; although the dev said to contact google, they also should be doing something to address this.  I think it's important for the dev to support people who paid for the app--this will be an issue going forward with the android system so they should work on a fix yesterday.

**Comment by xmaciek82** [comment]
I really hated to do this but I lowered my rating for the app in Google Play  since we didn't get much of  a response (I'll change it back once Wavelet is working).  
Response was to my lower rating was:
_I'm aware of the issue. Google changed a lot of code where Wavelet hooks into the system with this device. Right now they're looking into the issue because it's a platform bug. I'll try to come up with a temporary fix in the meantime._

Also,  can someone point me in the direction of how to submit reports to Google for this problem?

**Comment by Pittvandewitt** [comment]
> Also, can someone point me in the direction of how to submit reports to Google for this problem?

https://github.com/Pittvandewitt/Wavelet/issues/305?notification_referrer_id=NT_kwDOABpEPbMxMjA2Mjc2MjAyODoxNzIxNDA1#issuecomment-2367371865

**Comment by Pittvandewitt** [comment]
An update is available in the beta test now.

**Comment by c0r3yz** [comment]
> An update is available in the beta test now.

I am using the beta and can vouch for this update; the error is gone and so far it's working much better. I know you said there are other features that you're waiting on an Android fix for, but this is a huge step in the right direction!

**Comment by cooperaj** [comment]
The temporary beta fixes work fine on my Pixel 9 Pro on Android 15.

Fingers crossed Google does something about the platform issue. I've seen how long they can take to fox things sometimes.

**Comment by Alikzus** [comment]
I have not tested enough on my Pixel 9 Pro to be able to tell if the beta is working or not, but I think it does. However, the Virtualizer effect is missing (the only effect present is the Bass tuner). AutoEQ and Virtualizer is what I am using, so I hope that it is temporary. The Buffer size setting is also gone.

![5816743117884343761](https://github.com/user-attachments/assets/beabadd9-15c7-4fbc-b3fe-6944be8cff05)

**Comment by jacbrooks** [comment]
The developer said there some effects are not compatible with the new audio system in the Pixel 9. He might be able to add it back at a later.

**Comment by bbnn12** [comment]
works now on 9 pro XL a15!

**Comment by Fishman0919** [comment]
I seem to be having the same issue but found a workaround that works for me on my Pixel 9 Pro XL. The problem for me seems to be the lack of the buffer setting showing, so it can't be adjusted and I'm getting bass pops. I have Poweramp Music Player so I switched from Musicolet back and used the the preamp setting in Powreamp to lower the volume to about around -2.0 to where the popping/clipping stopped. On some bass heavy music I can sometimes notice a pop or 2 but lowering the volume a bit more (to -3.0'ish) fixes the problem. 

Hope this helps someone.

**Comment by NickMaga** [comment]
I can't stress enough the fact that in 2026 it still doesn't work, I just switched to a pixel 9 pro xl from a pixel 6 and without wavelet working I'm lost. How's it possible that there's no fix for it?

**Comment by c0r3yz** [comment]
> I can't stress enough the fact that in 2026 it still doesn't work, I just switched to a pixel 9 pro xl from a pixel 6 and without wavelet working I'm lost. How's it possible that there's no fix for it?

Been working fine for a while now... Maybe make sure you're up to date and check to make sure you allowed all the necessary permissions and settings.

**Comment by NickMaga** [comment]
> > I can't stress enough the fact that in 2026 it still doesn't work, I just switched to a pixel 9 pro xl from a pixel 6 and without wavelet working I'm lost. How's it possible that there's no fix for it?
> 
> Been working fine for a while now... Maybe make sure you're up to date and check to make sure you allowed all the necessary permissions and settings.

I've given it dump and notification permissions, also everything is up to date. Still not working for some reason. I tried deleting and reinstalling the app with no success, removing notification access and giving it back. Still no luck

**Comment by TheCodingRabbit** [comment]
Sooooo... Pixel 9 Pro XL User here, this bug seems to be back with yesterday's Android 17 qpr1 update :// worked like a charm before, now can't get it to work with said error. Already tried uninstalling, rejecting and granting permission, restarting device, lowering buffer size and the trick with ticking the effects off and back on again.
