### ISSUE TITLE
Request for Support: Parsing Error with Wavelet on Oppo A5s (Android 8)

### ISSUE THREAD

**Issue by devnadhjyothis** [Pittvandewitt/Wavelet#307]
Dear Wavelet Developer,

I hope this message finds you well. I am reaching out to seek assistance regarding an issue I encountered while trying to install the Wavelet app on my Oppo A5s, which is running Android 8. 
I have heard vast amount of positive comments 
From my friends and family who use your services.Unfortunately, I am receiving a "parsing error" during the installation process, and I am unable to proceed with using the app.

Here are the details of my issue:
- Device Model:Oppo A5s
- Android Version: 8.1
- Issue Description: I receive a "parsing error" when attempting to install the Wavelet APK.

I have tried downloading the APK from various sources and ensured that "Install from Unknown Sources" is enabled, but the issue persists.

Could you please provide any guidance or suggestions to resolve this issue? Your assistance would be greatly appreciated.
I look forward to future updates in the app

Thank you for your time and support.

Best regards,  
Devnadh 

---

**Comment by Pittvandewitt** [comment]
Sorry but Wavelet is available only on Android 9 or up. There is no way to make it work on older versions.
