### ISSUE TITLE
AutoEQ not showing?

### ISSUE THREAD

**Issue by MerBudd** [Pittvandewitt/Wavelet#308]
Hi, I have a Samsung Galaxy S23 Ultra and want to grab the preset for my headphones from AutoEQ. However, I cannot find the AutoEQ menu that was there before. I also cannot find any way to manually import any configuration. Was this removed, orrr?

I tried searching if this was removed, didn't find anything. I also tried searching for my issue, but couldn't find an answer that worked. I have both DUMP and Notification permissions granted.

**Comment by Pittvandewitt** [comment]
AutoEq was not removed. It will be available if your headphones are connected. If you need more support, please contact me via email.
