### ISSUE TITLE
Autostart with foobar2000 possible on a Xiaomi phone?

### ISSUE THREAD

**Issue by SoilnRock** [Pittvandewitt/Wavelet#313]
Any chance someone could provide me with some help on how to get Wavelet to autostart with foobar2000 on my Xiaomi android phone? I have done all the things like locking the app, granting background autostart and disbling power saving.
Still it doesn't autostart when I play music with foobar2000. Maybe I'm missing something and this is not possible (atm)?

Thx for any info!

**Comment by Pittvandewitt** [comment]
foobar2000 doesn't support external equalizer applications like Wavelet. There are 2 ways you can get Wavelet to work with foobar2000. First is enabling legacy mode, but in this mode not all options are available. Second is by enabling the [enhanced session detection mode](https://pittvandewitt.github.io/Wavelet/Settings/#enhanced-session-detection). It requires a bit more effort to set up, but once you do most music sources will work with Wavelet.

**Comment by SoilnRock** [comment]
Thx for your response, I have granted Wavelet both, DUMP and notificagtion access.
I don't understand step 3 however: "Go to notification listener access and enable the permission for Wavelet"

Any help is appreciated!

**Comment by Pittvandewitt** [comment]
Thank you very much for the support.
The notification listener can be enabled by opening the settings in Wavelet and clicking the option at the bottom.

**Comment by SoilnRock** [comment]
Ah, couldn't select it because I had legacy mode enabled. The option was actually already activated but it doesn't seem to make Wavelet start when I begin listening to music with foobar2000.
If you want/need more informatino I would be happy to provide.
Meanwhile I can sort of live with legacy mode and manual starting of Wavelet.

**Comment by Pittvandewitt** [comment]
Wavelet does not detect foobar2000 playback because the player does not implement a [MediaBrowserService](https://developer.android.com/media/legacy/audio/mediabrowserservice) or [MediaSessionService](https://developer.android.com/reference/androidx/media3/session/MediaSessionService). Wavelet needs to be able to query its package to obtain the uid.
Maybe the developer will add it in a future update.

**Comment by SoilnRock** [comment]
Thx for the info, I forwarded it to the foobar developers right away. Wavelet is SO GOOD!

**Comment by Pittvandewitt** [comment]
Thank you!

For foobar2000 to implement support for audio processors the right way, these are the instructions: https://github.com/Pittvandewitt/Wavelet/issues/32#issuecomment-691476597
