### ISSUE TITLE
New phone - Not seeing purchase

### ISSUE THREAD

**Issue by kvaaen** [Pittvandewitt/Wavelet#314]
Just moved to a new phone. But the app wont "see" my purchase on former phone. Even though i try and open through Google play store

**Comment by Pittvandewitt** [comment]
Your purchase is tied to your Google account. This means your purchase will transfer to your new device if you log in with the same Google account. In case your purchase is not recognized, please try the following: https://pittvandewitt.github.io/Wavelet/Troubleshooting/#in-app-purchase-no-longer-available
