### ISSUE TITLE
Effects not working on latest Android 

### ISSUE THREAD

**Issue by asterisk-ragavan** [Pittvandewitt/Wavelet#315]
The reverb effect and virtualization is not working 
I have attached the screenshot of the error, using the latest version from the Play Store 

![Screenshot_20240923-120024](https://github.com/user-attachments/assets/e2efaf88-2d3c-40aa-a553-99a5ae1c5aa2)

**Comment by Pittvandewitt** [comment]
Can you provide more information? What device do you use, which android version, does it happen only if headphones are connected, which session detection option are you using (legacy, regular or enhanced session detection mode)?

**Comment by asterisk-ragavan** [comment]
Usb dac : fiio ka11 
Device : pixel 9
Android version : Android 15

I have root access: can provide you the logs if needed

**Comment by Pittvandewitt** [comment]
Thanks for the gesture. I have what I need for the moment.

The issue you opened is the same as https://github.com/Pittvandewitt/Wavelet/issues/305, so I'll continue the topic there.

Please read my comment https://github.com/Pittvandewitt/Wavelet/issues/305#issuecomment-2367371865
