### ISSUE TITLE
Sound dose support?

### ISSUE THREAD

**Issue by amery** [Pittvandewitt/Wavelet#316]
Hi, would it be too out of scope to add support for sound dose? It's fairly annoying that Android 15 automatically pulls the software volume down when using a DAC with dedicated volume control and there is no configuration setting to disable it. 

Fiio Q3 + pixel 8a on android 15.

https://source.android.com/docs/core/audio/sound-dose

**Comment by Pittvandewitt** [comment]
All sound dose features are locked behind a privileged permission and a hidden API. All this material is exclusively available to OEMs.
