### ISSUE TITLE
Channel Balance Only Affects Lower Frequencies

### ISSUE THREAD

**Issue by HaiRon97** [Pittvandewitt/Wavelet#318]
Recent update broke channel balance. 

Set one to -9.9 (e.g. left) and the other (e.g. right) to -0.1 and only the lower frequencies get adjusted.

**Comment by Pittvandewitt** [comment]
Good catch. It will be fixed in the next beta version.

**Comment by Pittvandewitt** [comment]
Resolved in version 24.11
