### ISSUE TITLE
Switching to beta and losing Pro license.

### ISSUE THREAD

**Issue by koxaman** [Pittvandewitt/Wavelet#319]
Hello,

I switched to beta, found that wavelet works better than android 15 - pixel 7, and I can help you with your work with my experience. However, the auto eq bass... etc. is not visible, as if he lost my pro license. I have already reinstalled, restarted the phone but nothing.

Not work :( - https://pittvandewitt.github.io/Wavelet/Troubleshooting/#in-app-purchase-no-longer-available

**Comment by Pittvandewitt** [comment]
It sounds like you don't have any headphones connected. More options will appear if you do. Can you please send me an email instead if you need more support?

**Comment by koxaman** [comment]
I got home and it connected to the soundbar, then it activated within a couple of seconds, now it's good with headphones too.
