### ISSUE TITLE
Wavelet Support

### ISSUE THREAD

**Issue by Vivek0004** [Pittvandewitt/Wavelet#32]
How can i add wavelet support for my app
Please give me reply
i will be constantly waiting

**Comment by Pittvandewitt** [comment]
If you generated a `MediaPlayer` object, you can call `getAudioSessionId()` on it. This sessionID should be broadcasted by sending [this intent](https://developer.android.com/reference/android/media/audiofx/AudioEffect#ACTION_OPEN_AUDIO_EFFECT_CONTROL_SESSION) whenever music playback is starting/resuming.
If music playback is stopped or paused, you should always broadcast [this intent signal](https://developer.android.com/reference/android/media/audiofx/AudioEffect#ACTION_CLOSE_AUDIO_EFFECT_CONTROL_SESSION) to close the audio session, else effects will stay applied and the audio effect objects attached by the equalizer application won't be released.
It is good practice to reuse the same session ID as long as your music player application is in use.

Extras: 
https://developer.android.com/reference/android/media/AudioManager#generateAudioSessionId()
https://developer.android.com/reference/android/media/MediaPlayer#setAudioSessionId(int)
https://developer.android.com/reference/android/media/MediaPlayer#getAudioSessionId()

**Comment by Graphite23** [comment]
Are there any intent signals (or perhaps an Activity) that will enable Wavelet in Legacy mode.  So I don't have to go through ADB and give it full DUMP permissions and Notification access?  I can send intents and launch activities in Tasker.

**Comment by kairusds** [comment]
> If you generated a `MediaPlayer` object, you can call `getAudioSessionId()` on it. This sessionID should be broadcasted by sending [this intent](https://developer.android.com/reference/android/media/audiofx/AudioEffect#ACTION_OPEN_AUDIO_EFFECT_CONTROL_SESSION) whenever music playback is starting/resuming. If music playback is stopped or paused, you should always broadcast [this intent signal](https://developer.android.com/reference/android/media/audiofx/AudioEffect#ACTION_CLOSE_AUDIO_EFFECT_CONTROL_SESSION) to close the audio session, else effects will stay applied and the audio effect objects attached by the equalizer application won't be released. It is good practice to reuse the same session ID as long as your music player application is in use.
> 
> Extras: https://developer.android.com/reference/android/media/AudioManager#generateAudioSessionId() https://developer.android.com/reference/android/media/MediaPlayer#setAudioSessionId(int) https://developer.android.com/reference/android/media/MediaPlayer#getAudioSessionId()

I tried adding that to a game and it somehow doesn't work https://github.com/kairusds/osu-droid/blob/82eb411a6259d1d469ea9d2ebe3e812a9942991e/src/ru/nsu/ccfit/zuev/audio/serviceAudio/SongService.java#L41
