### ISSUE TITLE
Unable to open app, brings me to Play Store instead.

### ISSUE THREAD

**Issue by jarelllama** [Pittvandewitt/Wavelet#323]
Hi. I'm on GrapheneOS and am not signed into a Google Account. Upon opening Wavelet I immediately get sent to the Google Play Store app.

**Comment by SondreHusevold** [comment]
Same here. Is this an intentional change or a regression? Downgrading to 24.05 works, however it comes with the downside of no Pixel 9 support.

**Comment by Pittvandewitt** [comment]
It has to do with the integrity protection. I'll turn it off for the next release which will be rolling out gradually later today.

**Comment by jarelllama** [comment]
Fixed in 24.11. Thanks!
