### ISSUE TITLE
EQ adjustment broken in 24.10

### ISSUE THREAD

**Issue by Olrosse** [Pittvandewitt/Wavelet#324]
adjusting the EQ is behaving really weird for me on 24.10, adjusting 500hz also seem to adjusts bass and lowering it makes everything sound very tinny, same happens when enabling equal loudness, I've reverted back to 24.05 and everything sound normal again, the device I'm on is an xperia 1 VI running on android 14 and I was listening on speakers, i haven't tried aux or Bluetooth so I don't know if it affects that as well or if it's just on speakers

**Comment by franciscowilhelm** [comment]
Got the same / similar issue with the newest version from Play Store as of 2 November. Even if I have an EQ with miniscule changes on, it makes the sound very muddy (like a bass shelf up to lower mids). On Fiio M11 Plus LTD - Android 10. Playing back.

**Comment by franciscowilhelm** [comment]
Bug seems fixed for me. Thanks!
