### ISSUE TITLE
Youtube support?

### ISSUE THREAD

**Issue by tbmny** [Pittvandewitt/Wavelet#34]
Any change of adding support for Youtube?

**Comment by Pittvandewitt** [comment]
It is up to YouTube to implement support for audio processing. If you wish to process content from YouTube, the only option would be to use a different YouTube client that has support for audio processing implemented, such as [NewPipe](https://newpipe.schabi.org/). Please note that NewPipe has a [bug](https://github.com/TeamNewPipe/NewPipe/issues/2373) causing its sessions not to close properly.
