### ISSUE TITLE
Import Parametric EQ

### ISSUE THREAD

**Issue by 27niro** [Pittvandewitt/Wavelet#37]
Definitely among the most powerful tools to hit the audio game! Thank you for this blessing.

Appreciate the import Graphic Eq option, it gets on the nerves to calculate gain for 127 bands for one go though.

You know us enthusiasts can't live without Parametric eq.. please.

**Comment by Pittvandewitt** [comment]
Thank you for the kind words.
Android does not support parametric filters unfortunately. If you use the [AutoEq](https://github.com/jaakkopasanen/AutoEq) tool, you don't have to calculate each band manually.

**Comment by Salman7236** [comment]
is it possible now? poweramp has them.
