### ISSUE TITLE
Pandora Support

### ISSUE THREAD

**Issue by apederson94** [Pittvandewitt/Wavelet#4]
Any chance for full Pandora support?

Currently in order to get Wavelet to correctly process the audio form Pandora I must turn all features off and then back on again for each song in order for them to activate correctly.

**Comment by Pittvandewitt** [comment]
It doesn't seem that Pandora has audio session broadcasting implemented, so you must be using legacy mode. Legacy mode behaves different across devices, hence the name.
My suggestion is to make a feature request to Pandora asking them to implement session broadcasting, so you can use Wavelet in default mode, which is guaranteed to work.

**Comment by yoinx** [comment]
I opened a thread for this on Pandora's forum since they don't seem to have a bug reporter.

https://community.pandora.com/t5/Android/Wavelet-Audio-Session-Broadcasting/m-p/23296#M3026
