### ISSUE TITLE
Permanent Notification

### ISSUE THREAD

**Issue by A-l-e-k-s-G** [Pittvandewitt/Wavelet#40]
I always have a notification from wavelet in my Notifications Overview that says "Apps using Wavelet". 
It does not list any apps, not when they are running (e.g. Spotifiy) neither when they are closed.
I see the notifaction also when the EQ is not on (all sliders to the left). Is this the intendet behaviour?
Is it possible to just display the icon in the top bar only instead of the notifcation in the Notifications Overview and only display it when wavelet is enabled.

Android 11
wavelet 20.10

**Comment by Pittvandewitt** [comment]
In some cases the notification is not removed automatically. You should be able to dismiss notification when no apps are listed. It is not possible for me to show a different type of notification, else the service will not be launched as a foreground service: https://developer.android.com/guide/components/foreground-services
The service must run when music playback is detected, else it will not be possible to attach audio effects to that session anymore.

**Comment by A-l-e-k-s-G** [comment]
Ok did not know that.
Maybe it is possible to at least make an option to have a smaller notification with only one line.
The notification not showing which app is using wavelet at the moment is a bug?
![Screenshot_20201116-031333](https://user-images.githubusercontent.com/47826323/99206021-9c067000-27ba-11eb-974d-cf275b61fef8.png)

**Comment by clintfred** [comment]
If you don't care about seeing the notification at all, you can just disable notifications from wavelet in your settings too. Works like a charm for me.

**Comment by auanasgheps** [comment]
Since the latest update I can't dismiss the notification when **nothing** is being played. Is the same for you?

**Comment by Pittvandewitt** [comment]
This issue is resolved in the current open beta build.
