### ISSUE TITLE
Limiter pre-gain

### ISSUE THREAD

**Issue by burgersnchips** [Pittvandewitt/Wavelet#41]
Hi, here to make a feature request for an additional slider in the limiter options please. 

If we could pre-amplify before we limit it would further help balancing the volume for consuming high dynamic range content quietly at night. Thanks

**Comment by Pittvandewitt** [comment]
The limiter in Wavelet makes use of the DynamicsProcessing library shipped with Android. Unfortunately there is no parameter to control the pre-amp. This makes it not possible to fulfill your request. I suggest to use the Channel Balance feature to balance out the volume. It is applied first in the chain.
[Limiter documentation](https://developer.android.com/reference/android/media/audiofx/DynamicsProcessing.Limiter#Limiter(boolean,%20boolean,%20int,%20float,%20float,%20float,%20float,%20float))
[DynamicsProcessing](https://developer.android.com/reference/android/media/audiofx/DynamicsProcessing)
