### ISSUE TITLE
Support for OnePlus Buds.

### ISSUE THREAD

**Issue by RajneelDutta** [Pittvandewitt/Wavelet#42]
I have been loving this app. But I have noticed that there is an absence of support for OnePlus Buds and I am having to either work out my own EQ or use something like AirPods' settings. 
It would be amazing if you could include this in the subsequent rollouts.

**Comment by auanasgheps** [comment]
You're asking it in the wrong place. Presets are done [here](https://github.com/jaakkopasanen/AutoEq).

**Comment by Pittvandewitt** [comment]
https://pittvandewitt.github.io/Wavelet/Troubleshooting.html
