### ISSUE TITLE
Doesn't change to speaker eq

### ISSUE THREAD

**Issue by mkaflowski** [Pittvandewitt/Wavelet#44]
The app doesn't change to speaker eq after closing my airpods almost always when using legacy mode.

System: Android 11
Device Pixel 5
App version: 20.10

**Comment by Pittvandewitt** [comment]
The issue you describe is a known issue in the library used. You can find the ticket [here](https://issuetracker.google.com/issues/153552144)

**Comment by Pittvandewitt** [comment]
The MediaRouter library just got updated with a [possible fix](https://developer.android.com/jetpack/androidx/releases/mediarouter#version_121_3). Wavelet will be updated with the new version soon, stay tuned!

**Comment by Pittvandewitt** [comment]
This issue is fixed in the current build available in the beta channel
