### ISSUE TITLE
Supported Android versions?

### ISSUE THREAD

**Issue by auanasgheps** [Pittvandewitt/Wavelet#45]
Hi,
First of all let me tell how much **I LOVE** this app. Something definitive like ViperFX but without root was much needed. It's an instant hit, the AutoEQ integration is a KILLER feature and I'm going to buy the Pro version to support your work.

What are the actual requirements of this app to work? Does it use a specific Android API? I am asking because this app suddenly makes Android players much more attractive. Sony uses Android 9 whist other players use older versions.

**Comment by Pittvandewitt** [comment]
Thank you very much for the kind words and the support.
Wavelet makes use of most [AudioEffect ](https://developer.android.com/reference/android/media/audiofx/AudioEffect)libraries in Android. The DynamicsProcessing library is the most important one and was introduced in Android 9. Therefore Android 9 is the minimum requirement.

**Comment by AndyP2002** [comment]
It would be useful for the minimum version details to be posted somewhere obvious like the front page here or on PlayStore. My phone is quite old and PlayStore just doesn't show Wavelet at all if I search using the phone. I spent ages finding this post and the news that Android 9 is minimum.
My tablet is running Android 10 and PlayStore says Wavelet "may not be optimised for my device" but it seems to work ok.
