### ISSUE TITLE
Could not instantiate reverb and virtualizer

### ISSUE THREAD

**Issue by aiblis** [Pittvandewitt/Wavelet#5]
Hello.
I'm running into this issue where i get a toast notification whenever I begin a playback estating that it could not instantiate these two effects.
![Screenshot_20200518-204108_Nova Launcher](https://user-images.githubusercontent.com/12009164/82248506-8cf84f80-9948-11ea-8fc3-03a45d74cc13.jpg)
![Screenshot_20200518-204107_Nova Launcher](https://user-images.githubusercontent.com/12009164/82248515-8f5aa980-9948-11ea-8ac0-c6b113f1c03f.jpg)

Galaxy Note 9 Android 10

Thanks

**Comment by Pittvandewitt** [comment]
Hello,
What music player did you use?
It looks like your system does not contain the required libraries, which is very odd and may be an issue with your system.
I won't be able to fix this issue because it is not a bug in Wavelet.

**Comment by aiblis** [comment]
Hi! 
I use Google Play Music. Also tried Youtube Music with the same result though :(

**Comment by Pittvandewitt** [comment]
I pushed a new build that should reduce the amount of messages to only once.
A solution to the issue you experience would be to try a custom ROM that contains all required libraries.
