### ISSUE TITLE
no effect on samsung tab a

### ISSUE THREAD

**Issue by radopas** [Pittvandewitt/Wavelet#50]
Hi,
I can't make it work on my samsung tab neither in normal, nor in legacy mode. Wavelet works fine for the same headphones (sony wh1000xm3) on my phone and the same music apps, so i guess there is something with the samsung audio stack. It is strange, because Music EQ is working fine. 

Is there anything that i can help you to resolve this?

**Comment by Pittvandewitt** [comment]
Could you please verify if you have Wavelet set up properly in your device system so its not getting killed by your OS and has permission to start automatically? https://dontkillmyapp.com/samsung
Also make sure to use a music player that supports audio processing. You can find more information about it here https://pittvandewitt.github.io/Wavelet/#legacy-mode

**Comment by radopas** [comment]
Yes, it has the permissions to start automatically and also to change audio settings. I've applied changes proposed by dontkillmyapp. The application stays in the notification area, the headphone is recognized to be connected, and the AutoEq profile is selected. But nothing changes in the sound. I'm using the same music apps on my other phone (which is not samsung) and Wevelet works there with no problems as expected.

**Comment by Pittvandewitt** [comment]
It might have something to do with Sound Assistant. Another user reported that disabling this app fixed the issue. I am closing this issue because it is not an issue within Wavelet.
