### ISSUE TITLE
Only see EQ and Gain

### ISSUE THREAD

**Issue by marais33** [Pittvandewitt/Wavelet#51]
Running the paid version of Wavelet on a Pixel 3 with Android 11.  It only shows setting options in Legacy mode, and even then the only settings available are Equalization and Gain Control (Limiter and Channel balance).  Pressing the 3 bars on the top right only shows Legacy mode, Reduce clipping, and Help.  No other settings are available.  Is this just the way it is on this phone and version of Android or is there a way to get the other setting options?
Thanks.

**Comment by Pittvandewitt** [comment]
Features in Wavelet are shown dynamically. More options will show up if you connect your headphones, among which the unlocked features.
