### ISSUE TITLE
Show Current AutoEQ in Notification

### ISSUE THREAD

**Issue by locuturus** [Pittvandewitt/Wavelet#52]
I use 3.5mm "courage" port ear buds most of the time and the notification will say "Headset connected" and "Tap for more options" and there is all this empty space.  I would like to also see the name of headset the AutoEQ is set to in the notification.  If I connect USB C or Bluetooth headsets their names are displayed, and at least sometimes that also denotes the AutoEQ setting which is pretty useful.

**Comment by auanasgheps** [comment]
I totally endorse this option.

**Comment by Pittvandewitt** [comment]
If I were to implement this, then would pressing the notification open the AutoEq page or the screen it opens currently? And why prioritize AutoEq over any other option like the graphic equalizer. There are people who don't use AutoEq at all. They would rather see different information. If I had to please everybody, there should be some menu where you can select what information should be displayed and to which part of the app clicking the notification should lead. This would definitely defeat the simplicity, which is one of the key points of Wavelet.
Also, the notification does not leave much space on low DPI screens.
