### ISSUE TITLE
Sometimes EQ are swapped when using multiple headphones 

### ISSUE THREAD

**Issue by auanasgheps** [Pittvandewitt/Wavelet#53]
Hi,

I love Wavelet but from time to time I am experiencing an issue where EQ are swapped for different models.
I have a pair of Creative TWS which are _independent_ from each other and a pair of Sony WH-1000 XM3, that's 3 in total for the OS.

So I configured Wavelets for all three models (2 for Creative and 1 for Sony). Most of the time the app will remember and assign the right EQ to the connected headphone, but sometimes doesn't do this so it assigns the wrong one.

Are you aware of this problem? It does not always happen, so I don't know how to replicate. Maybe the binding method isn't very reliable. I haven't renamed my headphones.

#52 would also be appreciated. I bet this issue is happening more times than I open the app and check for the EQ.

**Comment by Pittvandewitt** [comment]
This issue should be resolved in the build that will be available in the beta channel in a few hours. Feel free to reopen this issue if you are still experiencing this issue.
