### ISSUE TITLE
Nothing is showing in OnePlus 7T and Nord phone, only a few options in Legacy mode

### ISSUE THREAD

**Issue by niyonsv** [Pittvandewitt/Wavelet#55]
I just installed the Wavelet app in my OnePlus 7T, but nothing is showing in the default mode and only Graphic Equalizer, Limiter and Channel Balance are showing in the Legacy mode. The same happens with the OnePlus Nord phone. Tried restarting the phone and resetting the app many times, also tried with many music and video apps.

I couldn't find any solution in internet too that's why I'm asking here. Please tell if any other information is needed.

Please check the attached screenshot link : https://imgur.com/a/tuwkHcU

**Comment by Pittvandewitt** [comment]
Features in Wavelet are shown dynamically. More features will show up when connecting your headphones for example.
For default mode to work, your music application must let know music playback has started (and stopped). More info here: https://pittvandewitt.github.io/Wavelet/#legacy-mode
Furthermore it is important that your device does not limit functionality; it must allow Wavelet to receive intents of music playback starting / stopping. Please follow the instructions on this page to set up your device properly: https://dontkillmyapp.com/oneplus
