### ISSUE TITLE
Wavelet - sampling and bitrate under bluetooth

### ISSUE THREAD

**Issue by u5459577** [Pittvandewitt/Wavelet#56]
I am just wondering, does Wavelet process audio in 16/44.1 over bluetooth if my LDAC bluetooth settings are set in the developer settings to this? Or does it always upsample to 16/48 if that is my system default as reported by Bitrate Checker (though I think this is for analogue connections)?

**Comment by Pittvandewitt** [comment]
I wouldn't be amazed if the bitrate checker app just calls [getNativeOutputSampleRate](https://developer.android.com/reference/android/media/AudioTrack#getNativeOutputSampleRate(int)), which defaults to 44.1 or 48khz. That said, Wavelet operates on the sample rate the used system libraries support, which is about any common sample rate. There is no upsampling going on.
