### ISSUE TITLE
Support for YouTube

### ISSUE THREAD

**Issue by Quinten0508** [Pittvandewitt/Wavelet#6]
There's a lot of people that use YouTube for music, and I noticed Wavelet does not detect YouTube as a music session. Could support for YouTube be added?
Thanks!

**Comment by Pittvandewitt** [comment]
Wavelet supports all apps that broadcast audio sessions. YouTube does not broadcast audio sessions, which means Wavelet can not attach to it. You can try if legacy mode works as explained in https://pittvandewitt.github.io/Wavelet/#legacy-mode

**Comment by Pittvandewitt** [comment]
In order for Wavelet to process music from YouTube, YouTube will need to implement session broadcasting. Wavelet picks up all broadcasted sessions automatically already.
My suggestion is to make a feature request to YouTube, but my bet is that it will be denied since YT Music exists.
