### ISSUE TITLE
Not Opening New Instance With AIMPlayer

### ISSUE THREAD

**Issue by Deswizard** [Pittvandewitt/Wavelet#62]
Wavelet will not recognize AIMPlayer for Android as a media instance and open the config menu.

**Comment by Pittvandewitt** [comment]
AIMP works just fine with Wavelet. It starts a session on startup. In case your device has an auto start or app launch setting, make sure Wavelet is allowed to start: https://dontkillmyapp.com/
Please provide more details such as what device you use, what version of Wavelet and AIMP you use and steps to reproduce in case you do not agree with the issue being closed.

**Comment by Deswizard** [comment]
Thank you for your response. It started working perfectly. I just had to
force close both apps first and then open AIMP and Wavelet popped right up.
I think because I already had AIMP playing while I installed Wavelet is
what caused the issue.

Thank you again.

**Comment by Deswizard** [comment]
Fixed.
