### ISSUE TITLE
Small request

### ISSUE THREAD

**Issue by datibor** [Pittvandewitt/Wavelet#63]
Hi, I have a wish for Wavelet: add phase inversion. One of my heaphones is not in phase. Also many of the speaker setups I have met has wrong polarity set up, even on large stages...which blows my mind. With a windows laptop is easy to correct with EqualiserAPO, I just multiply the left or right channel with -1. I pay you a beer if you implement this! Probably the best place for it would be the channel balance menu, with a toggle control. I appeciate a lot if you add it! Thank you! The app is really great!

**Comment by Pittvandewitt** [comment]
Unfortunately there is no library provided by Android that is able to inverse phase. The only software solution for Android I can think of is using [JamesDSP](https://github.com/james34602/JamesDSPManager). It comes with a custom library that allows for phase inversion and much more. You will need to have a rooted device for this.
The other solution would be to open your headphones and resolder the wires in one of the cups.

**Comment by datibor** [comment]
Well it's literally a multiplication with -1 on one of the channel. I know this because i wrote for winamp a DSP from scratch without any libraries 16 years ago. But thanks.
