### ISSUE TITLE
Add tidal support

### ISSUE THREAD

**Issue by tomavisar** [Pittvandewitt/Wavelet#64]
Please add tidal support

**Comment by Pittvandewitt** [comment]
It is up to the creators of Tidal to add support for audio processing. Their application has to inform the system through broadcasts when music playback starts and stops. If this does not happen, it is not possible to obtain the proper information needed to attach audio effects to that music session using the APIs provided by Android.
If you wish to make a feature request to Tidal, it may be useful to send them the following information: https://github.com/Pittvandewitt/Wavelet/issues/32#issuecomment-691476597

**Comment by justmwa** [comment]
FWIW, works for me now :)
