### ISSUE TITLE
Implementing Wavelet support in Android application (Java)

### ISSUE THREAD

**Issue by SagnikGanguly96** [Pittvandewitt/Wavelet#65]
Hi, I'm Sagnik Ganguly. I'm currently developing a music player for Android and I want to implement an equalizer so I've chosen Wavelet as I personally use it. But the problem is I couldn't find a way to implement it on my application, I even don't know if it's possible or not but I thought as the Wavelet is an open-source project there would be a way to implement on everywhere.
So I want to ask that how can I implement Wavelet on my Android application using Java (if it's possible)?

**Comment by Pittvandewitt** [comment]
Hello Sagnik, does the following link provide enough information for you? https://github.com/Pittvandewitt/Wavelet/issues/32#issuecomment-691476597

**Comment by SagnikGanguly96** [comment]
Okay I'll try it and let you know.
