### ISSUE TITLE
Graphic equalizer response slope is extreme

### ISSUE THREAD

**Issue by datibi** [Pittvandewitt/Wavelet#67]
Hi,
I noticed that the graphic equalizer sounds a bit wierd. I checked with the setup what I have (headphone clipped on a old smartphone). I noticed a very sharp frequency response, not the smooth curve how you represent it in the eq panel. Tested with 20-12000 hz sweep. Can you check it?

The test EQ preset
![Screenshot_2021-04-04-08-24-23-116_com pittvandewitt wavelet](https://user-images.githubusercontent.com/80484824/113499737-f5302f80-9520-11eb-895b-1e4a1eabefc7.jpg)

Sweep response when EQ off. 
![Screenshot_20210404-083242](https://user-images.githubusercontent.com/80484824/113499756-17c24880-9521-11eb-9373-ee4bdcf10b44.jpeg)

Sweep response when EQ is on, notice the sharp corners.
![Screenshot_20210404-083420](https://user-images.githubusercontent.com/80484824/113499791-6b349680-9521-11eb-85a0-f282173da40b.jpeg)

I just suggest to look into it if it can be improved.
I'm using it in legacy mode. The "reduce clipping" option affects the response a bit, makes the response slope even more sharp. I purchased your app.

**Comment by Pittvandewitt** [comment]
Thank you for providing the screenshots to visualize the issue. Currently the frequency response is not displayed correctly, which was an oversight, so I am definitely going to work on that. The image below shows the graph correctly, though this might not be the preferred solution.

![photo_2021-04-08_21-38-13](https://user-images.githubusercontent.com/1721405/114086449-eb0c8900-98b2-11eb-9863-13459026f7b9.jpg)


A second option would be to split the bands in smaller bands and keep the smooth graph as is. Basically how the image below shows. (Ignore the sample rate description)

![](https://www.headphonesty.com/wp-content/uploads/2019/07/SAMPLES.jpg)

**Comment by Pittvandewitt** [comment]
Fixed in the latest update.
