### ISSUE TITLE
Reverberation Option Missing

### ISSUE THREAD

**Issue by msoose** [Pittvandewitt/Wavelet#69]
Just got a pair of Sony XM4 headphones and noticed that the Reverberation option isn't enabled. Is there a reason this might be disabled per connected device?

Is it also possible to set a custom "global" personal eq preset that is applied to all outputs? Currently it seems I have to configure my eq for each device I connect to over bluetooth.

**Comment by Pittvandewitt** [comment]
Reverberation is available only if you connect your headphones and legacy mode is disabled.
Current implementation does not allow to use the same personal eq preset on each connected device. I will investigate if a global preset is possible without making creating a confusing UI.
