### ISSUE TITLE
Start clipping when screen locks

### ISSUE THREAD

**Issue by pehlm** [Pittvandewitt/Wavelet#7]
Thank you for making this app! Using Wavelet on a Samsung S20 with a stock Samsung (AKG) headphone is working okay with the screen unlocked but when it locks sound starts clipping, especially using reverberation. When I unlock the phone it's gone again. Using it with Dolby Atmos activated. The app is very good indeed though!

**Comment by Pittvandewitt** [comment]
Thanks for sharing your findings.
Yesterday I released an update that reduces possible clipping by increasing the time frame duration.
Can you please try if this resolves your issue? I want to ask you to try with Dolby Atmos disabled. It is hard to pinpoint the issue when a different eq might conflict.

**Comment by pehlm** [comment]
I've now tried with the new version using the reduce clipping option, have also disabled Dolby Atmos, it seems to work now. I don't hear any clipping when the screen locks. Thanks!
