### ISSUE TITLE
Auto Rotate even when auto screen rotation off?

### ISSUE THREAD

**Issue by chrixmll** [Pittvandewitt/Wavelet#70]
Im having this issue just with wavelet (using a Pixel 5 with newest Software).

My auto screen rotation is turned off, Wavelet rotates even when turned off. This happens with no other App (instead, a small icon shows up to confirm rotate when „auto screen rotate“ is off)

any chance to get it fixed?

**Comment by Pittvandewitt** [comment]
I am aware of this issue. It will be fixed in the next release.

**Comment by Pittvandewitt** [comment]
This issue is fixed in the current release.
