### ISSUE TITLE
Not working properly on Android 10

### ISSUE THREAD

**Issue by vinod9866** [Pittvandewitt/Wavelet#74]
Hello sir, greetings of the day. You suggested me to send an email regarding the issue i have reported in GitHub. To simply summarise the wavelet isn't working on Android 10 (tried in both redmi & Samsung) only graphical equaliser is working fine.I tried all the troubleshooting methods and settings but no use. The issue is only with Android 10, if I turn on other options it's just decreasing the sound with hyper boost of bass. Hope you got my view and able to fix this time. Regards!

**Comment by Pittvandewitt** [comment]
Is this issue still present in the 21.08 update? If yes, could you please provide me with detailed instructions on how to reproduce the issue, including music player used, which session detection mode is used (legacy, default or enhanced).
