### ISSUE TITLE
Need Help with custom EQ file 

### ISSUE THREAD

**Issue by hd3291** [Pittvandewitt/Wavelet#77]
these are the parametric frequency that i want to import from a file into wavelet but I'm clueless how to do it 

Preamp: -6.7 dB

Filter: ON PK Fc 7738 Hz Gain -2.5 dB Q 3.79
Filter: ON PK Fc 5957 Hz Gain 4.2 dB Q 3.54
Filter: ON PK Fc 5033 Hz Gain -2.7 dB Q 4.45
Filter: ON PK Fc 1435 Hz Gain -0.7 dB Q 4.68
Filter: ON PK Fc 17 Hz Gain 1.7 dB Q 2.43
Filter: ON PK Fc 19624 Hz Gain 4.7 dB Q 0.2
Filter: ON PK Fc 3055 Hz Gain 6.2 dB Q 0.91
Filter: ON PK Fc 835 Hz Gain 1.4 dB Q 2.2

THANKS

**Comment by SuzLEGIT** [comment]
Use these filter on Equalizer APO and then use this to convert the equalization to the format for wavelet https://github.com/zettonaender/eqapotographiceq-gui

**Comment by hd3291** [comment]
successfully created a Graphic EQ from @SuzLEGIT 's repo  and I've cross-checked too and its the same parametric eq in form of graphical EQ . But i'm not able to import it and use it on Wavelet.
After importing file .. it says " successfully imported graphicEQ.txt but everything looks same 
 please watch this screen record 
 
 https://drive.google.com/file/d/1wl-u_XVus3CE2y6VP7rIItTfYEgymKEx/view?usp=sharing

**Comment by SuzLEGIT** [comment]
I think Pittvandewitt himself state this problem before but Wavelet doesn't apply the preset you just import right away. You have to search it and apply it yourself

**Comment by hd3291** [comment]
I'm able to apply the GraphicEq file and it prompts too that that file has been imported ..but sadly no difference...its still not using the file

**Comment by hd3291** [comment]
Got it ..after importing it ..i have to search it too..!! Thanks for the help

**Comment by Pittvandewitt** [comment]
@SuzLEGIT That is correct. However, this behaviour will be improved in the next update. The imported file will then be listed directly.
