### ISSUE TITLE
Missing devices after update

### ISSUE THREAD

**Issue by Forever-Uselesss** [Pittvandewitt/Wavelet#78]
My audio device is missing from the auto eq list. 
Mainly Aukey device and Boat.
I am linking the respective website. 

Thanks for the app. I have upgraded to premium after a few days.
https://www.boat-lifestyle.com/
https://www.aukey.com/collections/audio

**Comment by Pittvandewitt** [comment]
Which ones exactly are missing after the update?

Also, please check out these links. The second one lists models of which you can import the graphiceq file in Wavelet.
https://pittvandewitt.github.io/Wavelet/Troubleshooting#headphone-model-not-listed-in-autoeq
https://github.com/jaakkopasanen/AutoEq/tree/master/results
