### ISSUE TITLE
Separate EQ for Wired & Wireless

### ISSUE THREAD

**Issue by ShivaCh-11** [Pittvandewitt/Wavelet#79]
For next update, Please include separate EQ selection by Wavelet when the Phone is connected to wired and wireless devices. i.e, Provide option to set seperate EQ for Wired and wireless earphones.

**Comment by Pittvandewitt** [comment]
This has always been a core feature in Wavelet.

If this is not how things are working on your device, please provide what behaviour you experience and what you would expect to happen.
