### ISSUE TITLE
support custom profiles?

### ISSUE THREAD

**Issue by w-** [Pittvandewitt/Wavelet#8]
Thanks for this app. 

I've generated a custom profile for my headphones because they weren't in the AutoEq repository. Is there anyway I can import these settings to use with wavelet?

**Comment by Pittvandewitt** [comment]
I had this idea in mind already. A function where you can import GrapicEQ strings will likely be added in the future.

**Comment by w-** [comment]
thx. look forward to it.

**Comment by Pittvandewitt** [comment]
Feature has been implemented in version 20.06
