### ISSUE TITLE
Reverb and virtualization not working

### ISSUE THREAD

**Issue by rakesh2485** [Pittvandewitt/Wavelet#83]
Device: Samsung galaxy buds live
Phone: Huawei mate 20 pro

I purchased wavelet app after purchasing my samsung galaxy buds live. Can you help me in getting reverb and virtualization to work? I use spotify and youtube music apps to listen to music. Thanks.

**Comment by Pittvandewitt** [comment]
Did you consult the troubleshooting page? There are some tips specifically about using sound effects with Bluetooth headphones. [https://pittvandewitt.github.io/Wavelet/Troubleshooting](https://pittvandewitt.github.io/Wavelet/Troubleshooting)
Some devices require legacy mode to be disabled to use certain effects.
On few devices, the virtualizer refuses to work when using a Bluetooth headphone.

**Comment by Pittvandewitt** [comment]
The 21.08 update released today fixes issues with virtualization not working over Bluetooth connections.
