### ISSUE TITLE
App malfunctions

### ISSUE THREAD

**Issue by dontobi** [Pittvandewitt/Wavelet#84]
I've been using Wavelet for a few weeks now and never had any problems, but with the latest update a bug seems to have crept in.

With the latest version (as of 22.06.2021) Spotify starts very sluggishly or VLC can no longer be operated after starting a video. At first I thought that it would not be because of wavelet, however, I do not have these problems when I uninstalled wavelet. Disabling wavelet did not change anything. I then downloaded old versions from apkmirror. With the build 21.06-2087 I do not have the problems. Only after that the problems appear again.

Enclosed some info about my device and the running software.
Device: Xiaomi Mi 10 5G
Android: 11
MIUI: 12.5
Rom: Xiaomi.eu Weekly 21.6.12

Translated with www.DeepL.com/Translator (free version)

**Comment by Pittvandewitt** [comment]
Looking through the commits between version 2086 and 2089, there is nothing I can find that can possibly be related to the problem you describe. I am also unable to reproduce this issue; both Spotify and VLC work as expected.
The few things I can think about it to try whether legacy mode is causing issues or if any other equalizer application may be trying to utilize the same library Wavelet uses.

**Comment by dontobi** [comment]
I can't rule out MIUI playing a role in the problems. However, I do not use any other equalizer apps and have not installed any other modifications.

**Comment by dontobi** [comment]
With the latest update, the problems have not occurred so far.

**Comment by dontobi** [comment]
Under MIUI, I have to grant the permissions again after every restart. Then it works. Apparently MIUI does not allow the rights permanently and across reboots.
