### ISSUE TITLE
GUI: Functions missing

### ISSUE THREAD

**Issue by el-ef** [Pittvandewitt/Wavelet#85]
Hi there,

this might be a stupid question. But can you tell me why several features disappeared from the Wavelet main menu on my Cepheus with Android 10?

![wavelet](https://user-images.githubusercontent.com/12398375/123175673-7644f600-d482-11eb-89e2-3e0fe8058acc.png)

Regards
el-ef

**Comment by SuzLEGIT** [comment]
connect your headphone

**Comment by el-ef** [comment]
> 
> 
> connect your headphone

Thanks, I just had to connect my DAC.
