### ISSUE TITLE
wavelet was unable to instantiate PresetReverb effects & Virtualizer effects issue

### ISSUE THREAD

**Issue by Pixeloblack** [Pittvandewitt/Wavelet#86]
2 days ago i unlocked wavelet by in app purchase but after purchase when i try to enable it shows this and after restart app it enabled effects but no change in sound so please fix it. in my case i set wavelet to don't optimise battery.

![Screenshot_20210622-211746](https://user-images.githubusercontent.com/86375656/123188885-78c34200-d4ba-11eb-8659-e5c9acf797b2.png)
![Screenshot_20210622-211749](https://user-images.githubusercontent.com/86375656/123188902-7b259c00-d4ba-11eb-8969-97403e28f95a.png)

**Comment by Pixeloblack** [comment]
If you can't solve please refund me

**Comment by Pittvandewitt** [comment]
There is something more wrong than just the issue you are reporting. The gain control features and graphic eq must always be visible if music playback is detected.
This implies that you are using a modified version for which I am not going to provide support for obvious reasons.

**Comment by Pixeloblack** [comment]
You've made a purchase from Thomas de Witt Software on Google Play.
Order number: GPA.3384-8530-2155-28843
Order date: 21 Jun 2021 09:16:58 GMT+5:30
Item
Price
Unlock all effects (Wavelet: headphone speciﬁc EQ)
₹179.00
[Gmail - Your Google Play Order Receipt from 21 Jun 2021.pdf](https://github.com/Pittvandewitt/Wavelet/files/6766594/Gmail.-.Your.Google.Play.Order.Receipt.from.21.Jun.2021.pdf)

**Comment by Pixeloblack** [comment]
if you still think that i am using a mod version then you should see above pdf

**Comment by onkarj422** [comment]
> There is something more wrong than just the issue you are reporting. The gain control features and graphic eq must always be visible if music playback is detected. This implies that you are using a modified version for which I am not going to provide support for obvious reasons.

Hello, same happening for me as well. Just bought the paid version. Reverb and virtualization worked for 4-5 songs and now it's throwing the same toast notification everytime.

![Screenshot_20220225-184641_Wavelet](https://user-images.githubusercontent.com/20082972/155721497-5dce8652-edea-42ca-8e5e-b8d3ce387c07.jpg)

Please, reopen this bug and if not planning to fix, please refund.

**Comment by raysoham1407** [comment]
Same issue happening for me as well. Official version installed from Play Store.

**Comment by titan2301** [comment]
Same issue is happening for me too. And I'm quite sure that I'm not using a modified version of the app because I downloaded it straight out of google play store. I would really appreciate if we can get a fix for this thanks!

**Comment by IndefiniteBen** [comment]
Same for me. Android 12 if that matters.

I can replicate the issue:
1. Listen to audio using a supported app (YouTube music in my case)
2. Open wavelet 
3. Turn off wavelet processing with the button
4. Turn it back on
5. Toast message appears

**Comment by sebas05000** [comment]
I have the same issue before it was working fine on a Samsung Galaxy Fold 3 with OneUI 4.1(Android 12) March Security Update
![Screenshot_20220412-175018_Wavelet](https://user-images.githubusercontent.com/66391171/163061617-72ade81f-7908-4ae2-b24e-14489b8e40b3.jpg)
![Screenshot_20220412-175025_Wavelet](https://user-images.githubusercontent.com/66391171/163061620-499744e7-ab58-4d65-a1a4-95b020852c53.jpg)

**Comment by JGurko** [comment]
I have the same issue, paid version.

**Comment by WeirdG** [comment]
Just noticed I'm experiencing the same issue. It was working fine on Android 13, but now it isn't. I'm using the paid version from the Google Play Store.

**Comment by d1pakda5** [comment]
I fix the issue. Just disable the legacy mode

![Screenshot_20230327_025134_Wavelet](https://user-images.githubusercontent.com/17035598/227805309-8347425b-d40e-419c-8986-96fc7ee44770.jpg)

Then the option will be visible
![Screenshot_20230327_025222_Wavelet](https://user-images.githubusercontent.com/17035598/227805327-3b30938b-c1e1-4937-a443-96cf1db0cb1a.jpg)

**Comment by k3lvin404** [comment]
My Phone got Updated to Android 14 recently and after that some of the options in Wavelet are disabled. No toast notifications come up when loading the app they are just disabled. I have tried wired IEM's Truthear Hexa and wireless headphones Galaxy Buds 2 Pro the following options are disabled in all of them. Please help as I have also provided all the required permissions.
![Wavelet Issue](https://github.com/Pittvandewitt/Wavelet/assets/15964496/b9eb1d7f-d9b5-4e36-85d7-2cc083c2698f)

**Comment by Pittvandewitt** [comment]
> My Phone got Updated to Android 14 recently and after that some of the options in Wavelet are disabled. No toast notifications come up when loading the app they are just disabled. I have tried wired IEM's Truthear Hexa and wireless headphones Galaxy Buds 2 Pro the following options are disabled in all of them. Please help as I have also provided all the required permissions. 

I was informed that searching for Wavelet in the Play Store and opening through there solves the issue. If not, please try following the instructions on this page: https://pittvandewitt.github.io/Wavelet/Troubleshooting/#in-app-purchase-no-longer-available
