### ISSUE TITLE
21.06 always clipping

### ISSUE THREAD

**Issue by braboobssiere** [Pittvandewitt/Wavelet#89]
after the updated to 21.06, i noticed very loud clipping/spiking noise whenever i fast foward YouTube video (or when it's loading and resume playing) which doesn't exist in previous version (21.03) (i tried max out buffer size and limiter setting, both doesn't help at all, limiter reduced it a bit but still very noticeable)

is it possible to add 'reduce clipping' function back?

**Comment by Pittvandewitt** [comment]
The reduce clipping option is replaced with the buffer size option. They fulfill the same purpose, but the latter allows for more control. It does not have anything to do with the noise you experience. However, I do have a possible fix for this issue.
