### ISSUE TITLE
TuneIn doesn't work in legacy mode

### ISSUE THREAD

**Issue by brietman** [Pittvandewitt/Wavelet#90]
Youtube does work in Legacy mode. TuneIn FM doesn't. Not sure what the reason is. Likely it has something to do how TuneIn work. But it also shows legacy mode doesn't always work for apps that doesn't work in normal mode.

**Comment by Pittvandewitt** [comment]
TuneIn probably uses the fast mixer [docs](https://source.android.com/devices/audio/latency/design#fastMixer)
That is not something I can fix. You might want to make a feature request to TuneIn asking for support for audio processing. Else you may want to try enhanced session detection.
