### ISSUE TITLE
notification icon always shows

### ISSUE THREAD

**Issue by ikonomov** [Pittvandewitt/Wavelet#91]
It would be nice if the app notification only shows when there's music playing.  Currently it's always showing when Wavelet processing is enabled.

**Comment by ikonomov** [comment]
I just saw the closed issue, so I need to elaborate further.  When I stop playing music from my music apps in a few seconds in Wavelet I do get the blank screen that says "No new music sessions have been started yet".  I assume that all music sessions have stopped and closed properly on my phone, yet still the Wavelet notification is active and showing.

**Comment by ikonomov** [comment]
Also signed up for the beta program on Google Play, there doesn't seem to be a beta update at the moment to test in case this was resolved as it was noted in the other issue post.

**Comment by ikonomov** [comment]
I just updated to version 21.07, not sure if this is a beta or not.  The issue still exists and the notification for Wavelet is always on whether or not there are music apps opened or playing.  After restarting there shouldn't be, and the notification is showing as soon as the phone boots back up.

**Comment by ikonomov** [comment]
Interestingly both Replaio Radio and Youtube Music does not properly close their music sessions.  I wrote out to Replaio requesting that they fix it, but how do we write out to Google requesting they fix one of the most popular apps in the world?
Google's reply: "Nope, we will not be fixing this issue, but we recommend you fix your DNA so you don't feel the need to use an external sound FX program."  Google are too busy making money to read feedback comments...

**Comment by Pittvandewitt** [comment]
From version 20.06 there is a big button at the bottom which allows you to start and stop the service (read show and hide the notification).
The advantage of the current behavior is that Wavelet will now pick up sessions on devices that would prevent Wavelet from starting when a music session starts, as long as the service is active. For example, Samsung, OnePlus, Huawei and Xiaomi have such auto start settings enabled by default that would break functionality.

**Comment by ikonomov** [comment]
Got it.  So then if undesirable to have the notification showing all the time the only option is to turn off notifications for Wavelet in the app settings?

**Comment by ikonomov** [comment]
> From version 20.06 there is a big button at the bottom which allows you to start and stop the service (read show and hide the notification).
> The advantage of the current behavior is that Wavelet will now pick up sessions on devices that would prevent Wavelet from starting when a music session starts, as long as the service is active. For example, Samsung, OnePlus, Huawei and Xiaomi have such auto start settings enabled by default that would break functionality.

Got it. So then if undesirable to have the notification showing all the time the only option is to turn off notifications for Wavelet in the app settings?

**Comment by Pittvandewitt** [comment]
You can choose to hide the notification completely in app settings.
It does not have big consequences if the service runs all the time. The RAM consumption will slightly increase if many sessions are open, but not by much. However it is adviced to restart your device from time to time, to get rid of audio sessions that were not closed properly by the music application that created them.
