### ISSUE TITLE
Audio processing not available for Google Chrome

### ISSUE THREAD

**Issue by Netherquark** [Pittvandewitt/Wavelet#92]
Hi!

The following is my setup:
[Evolution X 5.9.1 (Android 11) official](https://evolution-x.org/device/miatoll) on my [Redmi Note 9 Pro (curtana/miatoll)](https://www.mi.com/in/redmi-note-9-pro/). Also rooted with Magisk 23.

I use [nightly.diffuse.sh](https://nightly.diffuse.sh/) ([Github](https://github.com/icidasset/diffuse)) for music. I came across Wavelet and I wanted to try it. 
I gave the DUMP permission and the notification permission too, but to no avail. Wavelet showed a notification saying "Apps using Wavelet: Android System" regardless of whether I had Diffuse (which is a PWA I installed from Chrome) open or not.  Using Spotify did make Wavelet work, and I was able to input my headphones' model, namely AKG K361. But nothing happened with Diffuse. I hope it is possible to fix this, as I love the idea of Wavelet. Thanks in advance.

**Comment by Pittvandewitt** [comment]
If the notification states that Android System is being processed, it means you have legacy mode enabled. Disabling legacy mode is required to take advantage of the enhanced session detection mode.

**Comment by Netherquark** [comment]
does not matter
you can see a screen recording showing what is happening [here](https://photos.app.goo.gl/Zy9SiLdoZSW5huBi9).

**Comment by Pittvandewitt** [comment]
Thank you for the screen recording. That clears things up a lot.
I tried reproducing the issue and it seems that none of the audio effects are able to attach to the audio session started by recent versions of Google Chrome (chromium). These effects not being able to instantiate means that they are hidden from Wavelet.
There is no nice solution or fix to this problem. The thing that can be prevented is those effects being hidden by blacklisting chromium based browsers from audio processing.

**Comment by Netherquark** [comment]
Hey I switched to firefox about a week ago. On firefox, using the same website, the following shows up:

![Screenshot_20210819-092427_Wavelet.png](https://user-images.githubusercontent.com/65618735/130005129-bff7d122-e172-4824-be20-edc5a4798a71.png)


This is in normal mode, not legacy mode. I think it's working?

**Comment by Pittvandewitt** [comment]
Thank you for providing the screen recording. It helped analyzing the issue and while there is no true solution to this problem, at least it does no longer cause the settings to disappear in the september update (21.09)

**Comment by Netherquark** [comment]
[Firefox](https://photos.app.goo.gl/e7bw3fozWDoQPw2L7)

[Chrome](https://photos.app.goo.gl/rzWaRJqncX7vDrhg6)

[Settings screenshot](https://photos.app.goo.gl/avC3iWkfVdhasWBo8)


It all seems to be working perfectly ;)

Thanks man

**Comment by Netherquark** [comment]
Curtana, Android 12, ForkLineage

Enhanced detection w DUMP doesnt show Diffuse in Firefox. Legacy works though. Without dump, it works.
