### ISSUE TITLE
Google Play Services (billing service unavailable)

### ISSUE THREAD

**Issue by el-ef** [Pittvandewitt/Wavelet#94]
Hi,

do you plan to support devices without Gapps some day?

I am running Android with only MicroG and Aurora Store installed. Unfortunately, the app cannot recognize my purchase.

![wavelet](https://user-images.githubusercontent.com/12398375/127049149-ae8554cf-4eb9-4145-baa8-eade0e6a21e9.png)

Regards

**Comment by el-ef** [comment]
Addition: I installed the whole package over at microg.org/download.html
Now I get error 4. :(

**Comment by Pittvandewitt** [comment]
Although I understand your choice to run your device without gapps, it will be a very difficult task for me to create a payment system which includes hosting a separate app version including caching, spoofing protection and hosting and maintaining a stable licensing server. I will basically have to reinvent the wheel here.
I don't believe the cost will outweigh the benefits, sorry.
