### ISSUE TITLE
Virtualizer and bass tuner not working in miui k20 Android 11

### ISSUE THREAD

**Issue by vinod9866** [Pittvandewitt/Wavelet#97]
I've purchased to access premium features. But those not at all working on Bluetooth headset, working on plugged earphones. I've tried the trouble shooting tips but not working.

**Comment by Pittvandewitt** [comment]
This issue with the virtualizer is resolved in the 21.08 update. The bass tuner should work fine if effects in the gain control and equalization categories work too. If not, feel free to reopen this issue.
