### ISSUE TITLE
Duplicate AutoEQ profiles for Galaxy Buds+

### ISSUE THREAD

**Issue by Geekz45679** [Pittvandewitt/Wavelet#99]
There are duplicate AutoEQ profiles for the Samsung Galaxy Buds+. 

- One titled "Samsung Galaxy Buds+"
- And another titled "Samsung Galaxy Buds Plus"

They also have different settings. Is this intentional? I'm assuming not.

**Comment by Pittvandewitt** [comment]
This issue presented itself because the AutoEq database in Wavelet follows the results from the AutoEq project on Github. The issue will be resolved in the next update after this particular issue is resolved: https://github.com/jaakkopasanen/AutoEq/issues/309
